### ISSUE TITLE
Add cookiecutter template

### ISSUE THREAD

**Issue by OmegaDroid** [OasisLMF/OasisLMF#1]
Add the cookiecutter template to the package and add commands to the cli to generate a new model.

We should also simplify the template so that the cli can take advantage of default paths.

**Comment by OmegaDroid** [comment]
I've created a first attempt at the cc template integration (branch `feature/cc-template`).

I still need to add tests for the commands but it should give you something to take a look at.

Before deploying the new package involves installing git into the keys server docker file and update the requirements to install from the branch.

Before deploying the `model_execution_worker` needs to be built and pushed from the oasislmf package and the docker file in the template needs to be tagged to the new value. Currently I just build it locally.

I hope this all makes sense

**Comment by sr-murthy** [comment]
@OmegaDroid What's the status of the branch/PR for this issue?

**Comment by OmegaDroid** [comment]
I've not touched it in a while, I believe i got it to a state where a skeleton model project can be created but we need to check though to see if its sufficient.
