### ISSUE TITLE
in run_ktools use -s flag on kat for ORD elt reports

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1005]
## Issue Description

In order to make ORD event loss tables  in the same event order as legacy eltcalc report, please can you use the -s flag for kat when eltcalc is run with the ORD flags? There are three ELT flags as follows: eltcalc -M {filename} -S {filename} -Q {filename}

I noticed that when these flags are used (in a run with only ORD outputs), kat does not use -s on eltcalc, but it does on the legacy output.  

## Steps to Reproduce (Bugs only)

1. Use attached analysis_settings json to run PiWind.
2. compare event order within gul_S1_eltcalc.csv in default run with gul_S1_melt.csv in ORD run.
3. compare kat statements in run_ktools.sh between the two runs.

## Version / Environment information

oaisslmf 1.25.1

## Example data / logs

[analysis_settings.zip](https://github.com/OasisLMF/OasisLMF/files/8208031/analysis_settings.zip)

#939

**Comment by hchagani-oasislmf** [comment]
From ktools PR https://github.com/OasisLMF/ktools/pull/290, the `-s` flag has been dropped as `kat` can detect the incident table type and therefore will sort by default. There are some changes to `run_ktools.sh` script generation in the MDK that are necessary to reflect this change.
