### ISSUE TITLE
Expand PiWind tests to include more outputs 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1025]
## Issue Description
The test analysis settings files for PiWind https://github.com/OasisLMF/OasisPiWind/tree/develop/tests/ci 

only include the following outputs: 
```
     {
            "aalcalc": true,
            "eltcalc": true,
            "id": 1,
            "lec_output": true,
            "leccalc": {
                "full_uncertainty_aep": true,
                "full_uncertainty_oep": true,
                "return_period_file": true
            }
        }
```

These should be expanded to test all standard outputs and also include the newer ORD options

**Comment by johcarter** [comment]
you can assign this to me, @sambles  - I have a branch open on PiWind https://github.com/OasisLMF/OasisPiWind/tree/feature/ord_output_tests
