### ISSUE TITLE
ChanceOfLoss inconsistent between systems.  

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1056]
## Issue Description
The `ChanceOfLoss` field in **melt.csv** and **mplt.csv** output files shows rounding differences when executed on different systems. 
examples are `0.999875` vs `1.000000`. This throws off the CI testing when updating expected results.   

> **joh:** its calculated by modelpy and carried through the calculation as sidx -4
when it reaches summarycalc it is aggregated using a compounding product formula
the difference is that it used to be computed by getmodel pre-1.26 and now it is being computed by modelpy
so either modelpy is behaving inconsistently or there are floating rounding differences produced by summarycalc.

## Versions 
* oasislmf 1.26.0
* Ktools v3.9.0

## Example data / logs
![Screenshot from 2022-06-15 14-57-46](https://user-images.githubusercontent.com/9889973/173846265-46696f70-ea7b-4f83-8809-aa781377c79e.png)

**Comment by johcarter** [comment]
we are changing the calculation of ChanceOfLoss and I expect it will resolve this issue.
https://github.com/OasisLMF/ktools/issues/291
