### ISSUE TITLE
update 'ALCT' to 'CALT'

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1061]
## Issue Description

The new report Convergence in Average Loss Table (CALT) has been implemented as Average Loss Convergence Table (ALCT). 

The proposal for the new reports to ODS is CALT, not ALCT.

I suggest we update the implementation match the spec only once it has been approved (next ODS steering committee meeting) in case ALCT is preferred !!

Changes: in analysis settings json we have attributes alct_convergence and alct_confidence 
also update labels in ktools documentation.

**Comment by hchagani-oasislmf** [comment]
As changing the names of the `alct_convergence` and `alct_confidence` variables to `calt_convergence` and `calt_confidence` respectively has the potential to disrupt current users, both conventions should be supported. An informational message about the preferred naming convention can be issued to the user.
