### ISSUE TITLE
Add Command for Reinsurance 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#112]
Create command under `Oasislmf model  .. ` for Reinsurance

* Oasis file generation 
* Model execution

**Comment by mpinkerton-oasis** [comment]
Do we need separate commands? This is handled using the standard commands if reinsurance files are provided.

**Comment by sambles** [comment]
Yes sounds like a better idea, so extra arguments `--oed-scope-file-path`  and `--oed-info-file-path`

Added to: 
 `oasislmf model generate-oasis-files`
`oasislmf model run`
