### ISSUE TITLE
Blank CondPriority not handled porperly

### ISSUE THREAD

**Issue by fl-ndaq** [OasisLMF/OasisLMF#1122]
## Issue Description

CondPriority is not handled properly when some entries have a value and others are left blank.
Current recommended workaround if you have any conditions in the data is to set CondPriority to 1 rather than blank.

**Comment by johcarter** [comment]
Hi @fl-ndaq in which version of oasislmf do you see this please?  I can't replicate in 1.26.3.  I wonder if you can also provide a sample oed exposure set for me to test with please?

**Comment by fl-ndaq** [comment]
@johcarter that was discovered with a 1.23.10 worker. I'll send the files through slack as cannot share publicly.

**Comment by benhayes21** [comment]
done in 1.27.0
