### ISSUE TITLE
gulpy appears to hang when sample size is large

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/OasisLMF#1135]
## Issue Description
When sample size is large, `gulpy` appears to hang. The `work/` directory contains empty output files for `summarycalc`, indicating that no data from `gulpy` is being piped to `summarycalc`. The run completes successfully when `getmodel` and `gulcalc` are used instead of `modelpy` and `gulpy`.

## Steps to Reproduce (Bugs only)
Run the PiWind model with at least 5000 samples.

## Version / Environment information
MDK v1.26.3

**Comment by mtazzari** [comment]
Fixed in #1136
