### ISSUE TITLE
Post Loss Amplification

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#1142]
There is a requirement in the Nazare project to include a Post Loss Amplification factor to losses produced by the GUL calculation component (either gulpy, gulmc or gulcalc). This represents an uplift to the loss based in inflated costs to make good damage following a major event, since costs of labour, materials, loss adjustment expenses, etc. go up with demand.

The proposal is to have a static, event-by-event based uplift factor after GUL calculation based on intensity and size of event as a whole. The factor also needs to take into account location (to some degree) and coverage type.

Model developers will be able to provide an additional (optional) uplift factor file and if the file is present, GUL losses (sample and NI) should be uplifted by supplied factor per event

The file will include the following data:

- event_id
- uplift_area_id
- coverage_type
- uplift_factor

in addition to the uplift factor file, modellers can provide a mapping file from uplift_area_id to OED field(s) and values. This will allow, say, a modeller to provide, say, Country based uplift factors or custom zones to be mapped from a FlexiLoc field in the OED file to be defined.

Total loss should not capped at TIV - i.e. losses out of the gul calculation component can be larger than TIV and FM to behave as normal - i.e. not affected

Runtime user supplied secondary-factor option are also required. This would involve a user providing an additional, flat factor to be applied to the uplift factor from the file. For example:

![image](https://user-images.githubusercontent.com/11682391/200290162-6a0d911e-9002-4d8f-b6e8-180ebe668aa9.png)

The uplift calculation should apply after the GUL calculation and should be it's own module so that it can be applied to gulcalc, gulpy or gulmc...or complex model wrapper implementations. However, if elements from the logic can be inherited by gulpy/gulmc to improve performance, this would also be an option for development.

**Comment by johcarter** [comment]
There is an issue in the treatment of the user factor, that a user cannot apply a flat gross up factor without the model specifying them.  In the example above, if all supplied factors are 0, then the user 50% has no effect.  For discussion

**Comment by hchagani-oasislmf** [comment]
Closing as completed. Please see PR https://github.com/OasisLMF/OasisLMF/pull/1369 for `plapy` and PR https://github.com/OasisLMF/ktools/pull/354 for `placalc`.
