### ISSUE TITLE
OED enforce type int columns + filter empty rows 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#120]
https://github.com/OasisLMF/OasisLMF/blob/1.2.1/oasislmf/exposures/oed.py#L320-L323

Example file: 
```
ReinsNumber,ReinsLayerNumber,ReinsPeril,CededPercent,RiskLimit,RiskAttachment,OccLimit,OccAttachment,PlacedPercent,ReinsCurrency,InuringPriority,ReinsType,TreatyShare
1,1,WW1,1.00,0,0,0,0,1.00,USD,1,SS,1.0
,,,,,,,,,,,,
,,,,,,,,,,,,
,,,,,,,,,,,,
,,,,,,,,,,,,
```

**Comment by sambles** [comment]
smurthy [1:59 PM]
It’s not just empty rows - but expected data types should be enforced by setting data types for every column. Also, `NaN`s should be replaced by `None`, which would work better when doing comparisons of cell values, e.g.
```df = df.where(df.notnull(), None)```
Here `df` is any frame - this replaces `NaN`s and other non-standard null values with `None`.
There are a number of other Pandas improvements which could be made in the OED and reinsurance code, but I think this would be a minimum of work which needs to be done.

**Comment by sr-murthy** [comment]
I assumed that these reinsurance tests should be picking up this kind of stuff? The tests are probably not very deep. It's pretty easy to do to check that a frame that is being generated has the right data types for columns of interest. So some of the reinsurance tests should also possibly be updated.

**Comment by sr-murthy** [comment]
Had an issue with flaky test failure with one of these reinsurance tests the other day - I don't know whether it is related, but potentially things like this could also make the tests flaky. This may be true for all the reinsurance tests.

**Comment by sr-murthy** [comment]
One thing I forgot to add is that provided the frame has been loaded properly, empty rows can be removed with using

    df = df.dropna()

or alternatively if you don't want reassignment

    df.dropna(inplace=True)

BTW according to the Pandas documentation the following data values are treated as nulls

    By default the following values are interpreted as
        NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', 'N/A', 'NA', 'NULL', 'NaN', 'n/a', 'nan',
        'null'.

Duplicate rows can be removed using

    df.drop_duplicates(inplace=True)

**Comment by sambles** [comment]
Empty rows viewed as invalid data and should fail
