### ISSUE TITLE
(FM) Support for conditions on individual coverages and physical damage

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1210]
## Issue Description

We don't currently support special conditions which apply to either individual coverages or to physical damage, we only support conditions which apply to all coverages.

It is implemented for policy terms and we have the back-allocation framework in place to support the same at condition level.

Need to decide whether to add this to the list of FM features to complete in Nazare 2023.

**Comment by benhayes21** [comment]
@joh to check/add tests

**Comment by benhayes21** [comment]
some tests failing due to empty CondTag field - @sstruzik to fix

**Comment by benhayes21** [comment]
merged
