### ISSUE TITLE
`gulmc` fails if vulnerability functions are numbered in non-contiguous way

### ISSUE THREAD

**Issue by mtazzari** [OasisLMF/OasisLMF#1223]
## Issue Description
gulmc doesn't work properly when vulnerability functions are numbered in a non-contiguous way, e.g., 3, 5, 200.

## Steps to Reproduce (Bugs only)
Run `gulmc` on a model with vulnerability ids that are non-contiguous.

## Version / Environment information
linux
oasis v1.27.0

**Comment by benhayes21** [comment]
closing - fixed
