### ISSUE TITLE
Discuss documentation strategy

### ISSUE THREAD

**Issue by mtazzari** [OasisLMF/OasisLMF#1249]
## Issue Description
It seems to me that we have:
 - recent documentation 
 - (2+ yrs) old but likely still valid documentation 

but it is:
 - scattered over repositories
 - not necessarily reachable (due to by broken/outdated links)
 -  hidden in some directories
 - at times, out of sync regarding versioning, which makes it hard to understand what versions the docs applies to.
 
I think an overhaul to our docs strategy is in order to be effective in supporting customers.

**Comment by benhayes21** [comment]
Propose that we have "use case" approach with sections which can map across many use cases.

Suggested Use Cases

 - Model Developer
   - Building a new model
   - Converting an existing model
   - Managing versions and upgrades
 - Model Users
   - OED inputs
   - Results formats
   - Analysis options (sampling, etc.)
   - Oasis UI
- Installing/deploying the Oasis Platform 
  - Platform 1
  - Platform 2
  - Camel
  - Adding models
- Supporting an Oasis model deployment
  - workflow
  - error messaging


Sections
 - Oasis Model Data format(s)
 - Oasis workflow
 - OED
 - ODS Tools
 - Keys service
 - Ktools/pytools
 - Financial Module
 - Results (including ORD)
 - oasislmf package
 - Oasis platform (1&2)
 - Deployment options
 - Oasis UI
 - API
 - Errors
