### ISSUE TITLE
Support Risk Attaching 'RA' basis in reinsurance

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1250]
In the OED input files, Risks Attaching basis would be specified by setting AttachmentBasis = 'RA' for the relevant reinsurance contracts.

See [linkedin article](https://www.linkedin.com/pulse/excess-loss-risk-attaching-rad-basis-vs-occurring-during-joseph/) on Risk Attaching Basis vs Loss Occurring basis.

Risk Attaching basis requires us to take into account whether the underlying policies were incepted in the reinsurance period or not.

I've extended an example in the comments of the above linked in article to illustrate the rule.

![image](https://user-images.githubusercontent.com/11421733/231174888-ddecf290-ee84-44da-a500-ab68596bb035.png)

**Comment by johcarter** [comment]
To model these contracts accurately it would be necessarily to consider multi-year timelines and each events occurrence date relative to the reinsurance contract period and basis.  However the subgroup decided it is not worth doing this and to just use the policy inception date relative to reins inception date to filter out policies that incept before the treaty starts (Pol A in the example), in line with the way it is done in other platforms. For valid policies, reins terms will apply to all events ( a full year of risk), regardless of event occurrence and reins expiry dates.


**Implementation**

Assume Policies A-D are under the scope of a Reinsurance Treaty with AttachmentBasis = 'RA'
For those policies with PolInceptionDate >= ReinsInceptionDate (Pols B, C and D in the example), reinsurance terms should be applied for all events regardless of occurrence date, for Risk Attaching basis.   Pol A is excluded, meaning reins terms would not apply to any losses for Pol A.  

For AttachmentBasis = 'LO', the reins contract would continue to be modelled without reference to any dates.  i.e. Reins terms apply to all losses from Policies A-D.

**Comment by benhayes21** [comment]
cover this issue too

https://github.com/OasisLMF/OasisLMF/issues/149

**Comment by SkylordA** [comment]
Hi, just wanted to clarify a few implementation details.

1. Currently, the OED spec lists UseReinsDates, and the Reins/Pol Inception/Expiry Dates as Optional. However, I believe that these dates should be Conditionally Required on whether UseReinsDates is set to "Y".

    1. For now in code, I've set UseReinsDates default to "N" and the Reins/Pol Dates to empty strings. How should we handle the cases where there are no dates provided? Should we just apply the reinsurance terms regardless?

2. Would RA/LO be selected purely based on whether UseReinsDate is Y/N, or is there a separate argument that needs to be set for oasislmf?

3. For RA, how do we handle the case where PolInceptionDate > ReinsExpiryDate.

**Comment by aiste-kalinauskaite** [comment]
While I haven't gone through every detail just yet, I believe there is significant added value for our clients if we make certain dates conditionally required. Specifically, when the "UseReinsDates" is set to "Y" and/or when the Risk Attaching (RA) basis is utilized.

From my perspective, if RA is used, it is essential that the dates are populated. If these dates are missing, we'd need to rely on assumptions, which can be quite challenging to follow or even track down, even with thorough documentation. It could lead to potential misunderstandings and errors, which we should strive to avoid.

Additionally, in the context of RA, if the "PolInceptionDate" is greater than the "ReinsExpiryDate," wouldn't that suggest that the policy hasn't started yet? In that case, shouldn't such a policy be excluded from the specific reinsurance contract under consideration?
