### ISSUE TITLE
Parquet file generation is missing schema file

### ISSUE THREAD

**Issue by wska** [OasisLMF/OasisLMF#1266]
## Issue Description
It seems that when the option for paruqet_format is toggled on, it outputs some parquet files but without the header file. This means that we cannot effectively read any of the data.

## Steps to Reproduce (Bugs only)
1. Run an analysis with the option for parquet file enabled (and a relevant ORD output metric provided). We utilized the following:

2. Aquire the output files from the worker and inspect the results. There will be .paruqet files for the relevant output, but no schema file for them is provided.

## Version / Environment information
Oasis 1.27.1

## Example data / logs
analysis_settings == {'source_tag': 'newpiwindon1.27.1', 'analysis_tag': '73', 'model_supplier_id': 'OasisLMF', 'model_name_id': 'PiWind', 'number_of_samples': 8, 'gul_threshold': 0, 'model_settings': {'event_occurrence_id': 'lt', 'event_set': 'p'}, 'gul_output': True, 'gul_summaries': [{'id': 1, 'summarycalc': False, 'eltcalc': False, 'aalcalc': False, 'pltcalc': False, 'lec_output': True, 'leccalc': {'return_period_file': True, 'full_uncertainty_aep': True, 'full_uncertainty_oep': False, 'wheatsheaf_aep': True, 'wheatsheaf_oep': False, 'wheatsheaf_mean_aep': False, 'wheatsheaf_mean_oep': False, 'sample_mean_aep': False, 'sample_mean_oep': False}, 'ord_output': {'elt_sample': False, 'elt_quantile': False, 'elt_moment': False, 'plt_sample': False, 'plt_quantile': False, 'plt_moment': False, 'alt_period': False, 'ept_full_uncertainty_aep': True, 'ept_full_uncertainty_oep': False, 'ept_mean_sample_aep': False, 'ept_mean_sample_oep': False, 'ept_per_sample_mean_aep': False, 'ept_per_sample_mean_oep': False, 'psept_aep': False, 'psept_oep': False, 'return_period_file': True, 'parquet_format': True}}], 'il_output': False, 'ri_output': False, 'full_correlation': False, 'ri_summaries': []}

Below is the decompressed output from the relevant worker (The worker in question was the Oasis 1.27.1).
![image](https://user-images.githubusercontent.com/24625864/235953475-aea4fb89-d252-4dbb-9074-3b52f585a89b.png)

[newpiwindon1.27.1_PiWind_input_Files.zip](https://github.com/OasisLMF/OasisLMF/files/11383831/newpiwindon1.27.1_PiWind_input_Files.zip)

**Comment by wska** [comment]
Hi. I have obtained new information from my colleagues who are present at the ongoing oasis conference. It was said there are currently no plans to split output into multiple files. So the second question can be discarded.

Furthermore, after some investigation with the information that it is only meant to be single file outputs for each metric, we found out that there is indeed a schema embedded in the file as a meta-data attachment. It just requires a dedicated plugin to extract and read.

As such these concerns can be ignored. It seems to be working as intended.

**Comment by hchagani-oasislmf** [comment]
Hello @wska. Schemas for ORD outputs are available in the [ODS_OpenResultsData repository](https://github.com/OasisLMF/ODS_OpenResultsData). I do not know what you mean when you say that a header file is required to read the data. Using the analysis settings you listed above, I am able to read the parquet file that was created without issue:

```
$ ipython
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.22.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pandas as pd

In [2]: df = pd.read_parquet('gul_S1_ept.parquet')

In [3]: df
Out[3]: 
    SummaryId  EPCalc  EPType  ReturnPeriod          Loss
0           1       1       1        1000.0  3.400000e+06
1           1       1       1         500.0  3.400000e+06
2           1       1       1         250.0  3.400000e+06
3           1       1       1         200.0  3.400000e+06
4           1       1       1         150.0  3.400000e+06
..        ...     ...     ...           ...           ...
81          1       2       4          25.0  2.776789e+06
82          1       2       4          20.0  2.527836e+06
83          1       2       4          10.0  1.778104e+06
84          1       2       4           5.0  1.120864e+06
85          1       2       4           2.0  4.683638e+05

[86 rows x 5 columns]
```

I think I may have misunderstood your question. Would you point me in the right direction please?

If you run the entire process through the MDK, files are not overwritten in the generated bash script. You can take a look through the generated `run_ktools.sh` shell script file in the run directory should you be concerned. The only difference between the output parquet file names and their csv equivalents is the replacement of the `.csv` extension with `.parquet`. The rest of the file name is the same.

**Comment by hchagani-oasislmf** [comment]
Ah! No problem - our replies appear to have crossed. I'll delete my response.
