### ISSUE TITLE
Check and warn user of file encoding types in CLI

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#128]
Test file type using:
https://github.com/ahupp/python-magic

Log a clear warning like 'Expected UTF8'  found '<NON-Supported Encoding>' + an explanation of Unicode is, and how it is different from ASCII, and encoding type.

Otherwise input file transforms will probably fail with parsing errors

**Comment by sr-murthy** [comment]
I don't think an explanation of Unicode or ASCII is required - just a message saying that text (and generally this will be either CSV or JSON) files should be saved or prepared with UTF8 encoding.

**Comment by sambles** [comment]
obsolete issue, lxml no longer used
