### ISSUE TITLE
Assignment of loc_id and idx is not unique when using an EPA to split locations across more rows

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1300]
## Issue Description

In the gul file preparation, two fields are automatically added to the location file, loc_id and loc_idx as unique location counters.   When I use an EPA to modify locations (turning one location row into many), I can force update the LocNumber to be unique, but I cannot force the loc_id and loc_idx to increment across my split locations.  This results in some of the split locations being dropped in the final input files, and therefore not modelled.

A fix is required to support pre-analysis disaggregation using an EPA.

## Steps to Reproduce (Bugs only)

1.  Clone https://github.com/OasisLMF/OasisModels 
2.  Run oasislmf model run -C tests/test_4/oasislmf.json
3. Go to run folder inputs and compare raw_location.csv and location.csv.  location.csv has an extra location but the loc_id and loc_idx counters have not incremented for the third location.  Look at gul_summary_map.csv to see LocNumber 1_2 is missing.

## Version / Environment information

1.27.3

## Example data / logs

[location.csv](https://github.com/OasisLMF/OasisLMF/files/11676202/location.csv)
[raw_location.csv](https://github.com/OasisLMF/OasisLMF/files/11676203/raw_location.csv)
[gul_summary_map.csv](https://github.com/OasisLMF/OasisLMF/files/11676205/gul_summary_map.csv)

**Comment by johcarter** [comment]
Might you be able to take a look at this please @mtazzari ?

**Comment by benhayes21** [comment]
add step in pre-analysis hook to re-assign loc_id at the end of the process.

we should not write out loc_id to the new OED file since it is not a valid OED field.
