### ISSUE TITLE
Add post-analysis hook

### ISSUE THREAD

**Issue by philipoldham** [OasisLMF/OasisLMF#1317]
## Issue Description
We wish to have access to a post-processing hook. The post-analysis hook would have the same capabilities as the pre-analysis hook but be called after the analysis stage.

**Comment by benhayes21** [comment]
I think we need more information on this. From conversations, it sounded more like it was a "combining results"?

**Comment by JBADougBurns** [comment]
It would be good to have a conversation on this. Our intention for now is to use the OasisLMF output summaries to generate some additional metrics, specifically things like sensitivity indices.

**Comment by philipoldham** [comment]
We would want the post-analysis hook to be triggered _after_ writing results to disk, as the last thing to be run in an analysis. The hook should have the capability to access the input directory, the output directory, the model settings, and the model data (i.e. same as pre-hook but with the addition of the output directory).
