### ISSUE TITLE
Implement OED policy coverage terms in Financial Module

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#135]
Specifically fields PolDed, PolMinDed, PolMaxDed, PolType and PolLimit for coverages 1-5

Losses from site or combined terms must be back-allocated in order to apply coverage specific policy terms. requires a second iteration of fmcalc within the direct insurance calculation.

Member has provided worked example

**Comment by sr-murthy** [comment]
@johcarter This appears to be for the policy coverage level (OED level 7). As you know, in phase 1 the OED levels supported via the profiles are:

1. site coverage
2. site pd
3. site all
6. cond. all
9. policy all
10. policy layer

I assume this request is for phase 2.

**Comment by sr-murthy** [comment]
@johcarter This appears to be for the policy coverage level (OED level 7). As you know, in phase 1 the OED levels supported via the profiles are:

* 1 - site coverage
* 2 - site pd
* 3 - site all
* 6 - cond. all
* 9 - policy all
* 10 - policy layer

I assume this request is for phase 2.

**Comment by sr-murthy** [comment]
@johcarter It would be useful to indicate the additional OED terms required for Phase 2 in the OED spec. spreadsheet. A Phase 2 column could be added and marked for those additional fields needed for this feature and other related future FM features.

**Comment by sr-murthy** [comment]
Implemented

**Comment by johcarter** [comment]
This specifically relates to coverages 1-5 (6 is done) so this is still to do but not yet as it requires big changes.

**Comment by sr-murthy** [comment]
OK, I see that those columns were added to the policy layer level in the account profile, which means coverage type ID 6 (all (property damage + business interruption)).

**Comment by johcarter** [comment]
I think the original fm levels are still valid, @sstruzik 
the full list is ( with OED fields in brackets,  'XXX' representing Ded, DedType, Limit, LimitType, MinDed, MaxDed, DedCode, LimitCode)
1 - site coverage (LocXXX1Building, LocXXX2Other, LocXXX3Contents, LocXXX4BI)
2 - site pd (LocXXX5PD)
3 - site all (LocXXX6All)
4 - cond coverage  (CondXXX1Building, CondXXX2Other, CondXXX3Contents, CondXXX4BI)
5 - cond pd (CondXXX5PD)
6 - cond. all (CondXXX6All)
7 - policy coverage (PolXXX1Building, PolXXX2Other, PolXXX3Contents, PolXXX4BI)
8 - policy pd (PolXXX5PD)
9 - policy all (PolXXX6All)
10 - policy layer (LayerAttachment, LayerLimit, LayerLimit)

We can extend the levels to include account terms too.

**Comment by johcarter** [comment]
**Numerical differences** 

Floating point errors occur across all insured losses at the sample level. This means the individual gross loss samples may be different to 5/6 significant figures.

The gross loss results for a few test cases are more significantly different as a result of this change.
 
**Impact**

- The bigger changes are for test cases that have a policy maximum deductible and prior level deductibles. They only occur for samples when the maximum deductible is enforced.
- The total policy loss for these cases does not change. This means that outputs by all risks, portfolio, account and policy will not change, other than floating point errors affecting all gross losses.
- The differences are at the location/coverage level for the policy maximum deducitble test cases. The difference is a re-allocation of losses to locations within a policy for samples where a policy maximum deductible is enforced. The maximum observed difference is 9% at an individual location and sample level. This means, for example, that one location sampled loss is 9% lower, and another location under the same policy is 9% higher, compared with before the back-allocation code change.
- There could be a knock on effect on net losses, if location level reinsurance terms are applied to an affected location and sample.

**Test cases impacted**
Those with a policy maximum deductible combined with location or coverage normal deductible.
Validation tests reference: insurance_and_step

Test units impacted:
Q1_58
Q2_42
Q2_59
Q3_2
Q3_45
Q3_60
Q3_61
fm8

Note that there are other policy types which will be affected in the same way, but not covered by our tests. They are expected to be policies which have a maximum deductible somewhere in the hierarchy (e.g. condition or location level) with prior level normal deductibles (location or coverage, respectively).
