### ISSUE TITLE
Partition parquet vunrability data by vunrability_id

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1365]
## Issue Description
Work is required for lot3 performance to split **vulnerability.parquet** by `vulnerability_id` in a similar style as the footprint data. 

https://github.com/OasisLMF/OasisLMF/blob/44d0d5e30682107967811e39d248b7354bfbb313/oasislmf/pytools/getmodel/vulnerability.py#L124-L159

**Comment by benhayes21** [comment]
Works - need to test performance and then close
