### ISSUE TITLE
Apply limits to aggregated exposures

### ISSUE THREAD

**Issue by ANNOOSSY** [OasisLMF/OasisLMF#1374]
## Issue Description
Hello,
My exposure data is aggregated by county. I have the number of risks in each county. The Limit by building is 25,000.
I have trouble applying the limit on each individual building in the county. I don't want the limit to be applied on a county level, which the file seems to do.

Here's how my file is organized:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/BOUCHA~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/BOUCHA~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

PortNumber | AccNumber | LocNumber | CountryCode | AreaName | OEDVersion | GeogScheme1 | GeogName1 | ConstructionCode | OccupancyCode | IsAggregate | NumberOfBuildings | LocPerilsCovered | LocCurrency | LocPeril | LocLimitType1Building | BuildingTIV | LocLimit1Building
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Port1 | FSEC | 1 | MA | PROVINCE 1 | 2.0.0 | CRSL4 | County 1 | 5150 | 1050 | 1 | 15146.00 | QEQ | USD | QEQ | 0 | 277804294.30 | 25000.00
Port1 | FSEC | 2 | MA | PROVINCE 1 | 2.0.0 | CRSL4 | County 2 | 5150 | 1050 | 1 | 4432.00 | QEQ | USD | QEQ | 0 | 82331930.00 | 25000.00
Port1 | FSEC | 3 | MA | PROVINCE 1 | 2.0.0 | CRSL4 | County 3 | 5150 | 1050 | 1 | 8118.00 | QEQ | USD | QEQ | 0 | 149499361.40 | 25000.00
Port1 | FSEC | 4 | MA | PROVINCE 1 | 2.0.0 | CRSL4 | County 4 | 5150 | 1050 | 1 | 3239.00 | QEQ | USD | QEQ | 0 | 59054554.29 | 25000.00
Port1 | FSEC | 5 | MA | PROVINCE 1 | 2.0.0 | CRSL4 | County 5 | 5150 | 1050 | 1 | 1410.00 | QEQ | USD | QEQ | 0 | 26731488.57 | 25000.00

</body>

</html>

Please help me find a way to apply the 25,000 limit to each individual risk in the county.
Thank you very much!

**Comment by johcarter** [comment]
Hello, limits must be entered as aggregate, relative to the number of buildings.

For v 1.28.0 and later, in the file preparation stage, the TIVs will be equally split into n risks, where NumberOfBuildings = n.
If IsAggregate=1, then any deductible or limit value will also be equally split by n and applied to each sub risk. 

So I think entering 25,000 * n into LocLimit1Building  for each line in your example file and keeping the other fields the same will achieve your objective.

**Comment by ANNOOSSY** [comment]
Thank you very much.
I was trying to avoid this solution though, but I guess since the disaggregation is handled by the models, Oasis has "no say" on how the limits are distributed across risks of an aggregated location.
Much appreciated!

**Comment by johcarter** [comment]
Disaggregation is handled only by some models, so this is a simple system default rule we have introduced in order that aggregate risks are not modelled as single risks, regardless of what model you are running.

**Comment by ANNOOSSY** [comment]
Thank you for the clarifications.
