### ISSUE TITLE
Performance issue in get_exposure_summary

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1379]
## Issue Description

```
Oasislmf: 1.28.2 
Piwind: main 
Loc file size: 500k 
```

The function call `oasislmf.preparation.summaries.get_exposure_summary` can be disabled with the flag `--disable-summarise-exposure` the execution time with this enabled has a signification performance impact.  

Execution time **with** exposure_summary = **1496.88s**
Execution time **without** exposure_summary = **97.42s**

### Likely cause:
> **benhayes:**  I think it's because the `keys_df` input to `get_exposure_summary` is the concat of the keys and keys error files - and the keys error file has the no-returns for all perils, which is the **1.3GB**

> we need to rethink that. We should probably only include covered perils for the model from the model_settings file

**Comment by benhayes21** [comment]
Default keys server behaviour should return data for supported perils only
