### ISSUE TITLE
Flag required in oasislmf 1.28.X to turn off disaggregation. 

### ISSUE THREAD

**Issue by JCrane512** [OasisLMF/OasisLMF#1384]
## Issue Description
`oasislmf 1.28.3`  introduced disaggregation. As JBA's complex flood model already performs disaggregation itself, this has lead to disaggregation being run twice, once by JBA's code and once again by `oasislmf`.

## Steps to Reproduce (Bugs only)

1. Run any JBA Flood Model with aggregate rows in the portfolio. 

## Version / Environment information

It will happen on any platform. The affected `oasislmf` version is `1.28.X` and higher. The last working configuration is `1.27.X`. 

## Example data / logs

We were finding that this line was suggesting the problem to us, it was taking multiple hours, instead of the normal >10 seconds. 
`2023-10-26 17:14:16,700 oasislmf log@128:wrapper [1386675:140364176003072] [INFO] COMPLETED: oasislmf.preparation.gul_inputs.get_gul_input_items in XXX`

**Comment by johcarter** [comment]
Can we use this flag to disable the IsAggregate logic too? additional requirement from JBA

**Comment by benhayes21** [comment]
https://github.com/OasisLMF/OasisLMF/pull/1401
