### ISSUE TITLE
Net RI losses do not use -z in summarycalc

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#1394]
## Issue Description
Whenever Net Loss is called in fmpy (-n flag) then we need to apply -z flag in the subsequent summarycalc in order to not exclude 100% net losses

## Steps to Reproduce (Bugs only)
1. Run RI losses at a low level (e.g. location level)
2. compare portfolio level losses to the sum of the low level losses
3. some low level losses will be lost

**Comment by hchagani-oasislmf** [comment]
Currently, net loss is only called in `fmpy` for reinsurance. Therefore, the `summarycalc` flag `-z` can be applied to all instances of reinsurance loss computes. If we decide to change this behaviour in the future, we can revisit this.

**Comment by benhayes21** [comment]
Reopening, as this approach is having significant performance impacts
