### ISSUE TITLE
Implement OED peril fields

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#140]
Peril-fields: using peril fields to determine which perils are used (policy restrictions) and which financial conditions are used

**Comment by johcarter** [comment]
LocPerilsCovered (loc) and PolPerilsCovered (acc),  are both required fields. There may be difference in the field value for locations belonging to a policy if there are peril exclusions on certain locations, for example a policy covers all perils, but a location is excluded from flood because it sits on a river bank.   If running this policy against a flood model, then this location should be excluded from generating ground up losses (ie do not send to key server).
There can be duplicate location rows (same account number, location number, locperilscovered) if there are different location terms for each peril. In this case the LocPeril will differ.
Follow up question: are the perils specified in LocPerilsCovered always a subset of the perils specified in PolPerilsCovered?

**Comment by johcarter** [comment]
From Matt and Aiste:

We have 7 perils fields:

LocPerilsCovered (Mandatory)
PolPerilsCovered (Mandatory)

PolPeril
CondPeril
AccPeril
LocPeril
ReinsPeril (Mandatory)

Financial conditions / terms = limits or deductibles for coverages 1 to 6.

LocPerilsCovered refers to which perils are covered by the location irrespective of financial conditions applying to the location. You can have multiple rows per location, but LocPerilsCovered should always be the same for a location. (LocPeril can change from row to row within a location to indicate financial conditions which are different by peril). 

PolPerilsCovered refers to which perils are covered by the overall policy. There may be other conditions and financial terms that limit the coverage, but this is how a user tells that a peril is covered by this policy. Given that a policy is essentially a layer, this can also be thought of as the peril code which applies to the layer (but not the underlying policy limits / deductibles – these would be specified by PolPeril or CondPeril). You can have multiple rows per policy, but PolPerilsCovered should always be the same for a policy. (PolPeril and CondPeril can change from row to row within a policy to indicate financial conditions which are different by peril).

ReinsPeril refers to the perils covered by the reinsurance contract.


LocPeril refers to the location level financial conditions only (in the loc file)

Cond/Pol/AccPeril refers to the special condition / policy / account level financial conditions respectively (in the acc file)

LocPerilsCovered is NOT a subset of PolPerilsCovered because you may have layers that only cover a limited number of perils (for example separate wind and earthquake layers that apply to the same locations)

PolPerilsCovered is NOT a subset of LocPerilsCovered because within any given policy there may be specific locations where coverage is excluded for a specific peril (e.g. location is too high a risk – eg too close to a river)

PolPeril / CondPeril should be a subset of PolPerilsCovered

LocPeril should be a subset of LocPerilsCovered


Usage

The key-server should just use LocPerilsCovered to return area-peril keys for locations with a valid OED peril code

The FM will have to use all the other peril fields to work out whether coverage applies or not and the correct limits and deductibles to use for a given peril, e.g.

LocPeril is used to extract correct location financial terms for a peril being modelled.

PolPerilsCovered is used to identify which policies (layers) have coverage for a particular peril and PolPeril is used to pick out correct account, policy or conditions financial terms.

Ground-up loss should contain the loss for all locations with a valid LocPerilsCovered code

Gross (insured) loss should include the impact of all the peril codes apart from ReinsPeril

Net should include the impact of all the peril codes.

The exposure value that flows through into the result files should correspond to the loss perspective, so for the ground-up result files the exposure value should be the TIV just for those locations with a valid LocPerilsCovered for the peril being modelled.

For the insured loss (gross) perspective, the exposure value should be the exposure propagated through the financial-conditions taking into account the peril-codes.

**Comment by MattDonovan82** [comment]
hi @johcarter. Assuming this is still in progress - can we possibly get this back on the table when possible? I'll link it to the ODS repo.

**Comment by johcarter** [comment]
This is quite a big task and it will need to be prioritised. we can discuss at the next dev meeting perhaps.

**Comment by sstruzik** [comment]
plan to implement Peril support.

- [ ] in order to align the test with the new exposure logic, change all the current test to have AA1 for all the peril columns LocPerilsCovered, LocPeril, ...

- [ ] Pick WTC for single peril test and WW2 (WTC and WEC) for subperil test.
 remove the current DeterministicLookup logic

- [ ] by default if no Perils are given in exposure run, all perils in LocPerilsCovered will return a key.

- [ ] add a new parameter to exposure to specify extra column to aggregate by. So I'll keep the item level as is but we will be able to specify to the run that we also want the perils for the peril tests
