### ISSUE TITLE
Allow customising single vulnerability_ids

### ISSUE THREAD

**Issue by ncerutti** [OasisLMF/OasisLMF#1408]
## Issue Description

Improves on issue #1403, allowing for the amendment of single vulnerability_ids.

An optional vulnerability adjustments file may contain changes to specific vulnerability functions. If present and used, data relative to those vulnerability ids in the default vulnerability file will be overwritten by the custom values during the run.

**Comment by benhayes21** [comment]
examples required of difference between damage and distribution
