### ISSUE TITLE
Add an example of the vulnerability file selection to PiWind.

### ISSUE THREAD

**Issue by ncerutti** [OasisLMF/OasisLMF#1419]
## Add an example of the vulnerability file selection to PiWind.

Both footprint and vulnerability files can be selected using the corresponding entry in the analysis settings (footprint_set and vulnerability_set, under model_settings, see PR [#1406](https://github.com/OasisLMF/OasisLMF/pull/1406)). An example of this should be added to OasisPiWind (or OasisModels?).

**Comment by benhayes21** [comment]
Oasis Models rather than PiWind
