### ISSUE TITLE
Implement % & Min & Max deductibles in OED

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#142]
and apply to losses at same level as well as from preceding levels.

**Comment by johcarter** [comment]
I'm trying to run fm35 through MDK which is % loss deductible with min and max at policy level. the %loss type will be ignored and deductible treated as %tiv, but thats ok for now for the purposes of testing whether min and max work together. 
however the MDK fails to generate the files. i have checked i have all the required fields for MDK.
[fm35.zip](https://github.com/OasisLMF/OasisLMF/files/2680328/fm35.zip)

**Comment by sr-murthy** [comment]
@johcarter Just a thought from a glance at the source loc. and acc. files - I think you will end up with an FM table for this test case with items in level 9 (policy all) with positive values for all deductible terms (blanket, min. and max.), but there is currently no calc. rule (in the sub-layer calc. rule method) defined for the case when an item has positive blanket, min. and max. deductibles. If my thinking is correct, it means calc. rule IDs for all level 9 items will be null (`None`), which means the policy TC calculation will produce some policy combinations with nulls for calc. rule IDs, which causes that method to fail, whcih causes the `load_fm_items` to fail. I think that would explain the error you're seeing.

e.g. in `account.csv` you have

    ...,PolDed6All,PolMinDed6All,PolMaxDed6All,...
    ...,0.15,100000,150000,...

During the level FM terms generation the value of the blanket deductible for all level 9 items (obtained via `PolDed6All`) is calculated as 0.15 x item coverage TIV, e.g. for buildings coverage we get a blanket deductible of 0.15 x 1000000 = 150000, a min. deductible of 1000000 and max. deductible of 150000. But there's no calc. rule applicable for an item with these deductibles.

For reference, this is the link to the FM code where the sub-layer calc. rule method is defined.

https://github.com/OasisLMF/OasisLMF/blob/feature/add-deterministic-loss-generation-script/oasislmf/utils/fm.py#L245

You can see there is no calc. rule for the case when blanket, min. and max. deductibles are all positive. If you define one, then it will work.

**Comment by johcarter** [comment]
Until we support the dedtype field, we need to assign calcrule 21 to this scenario (deductible and min ded and max ded all >0).
When we implement dedtype field, if dedtype = 2 then we assign calcrule 21, if dedtype = 1 then we assign calcrule 19.

**Comment by sr-murthy** [comment]
I've pushed a fix for this in this branch

https://github.com/OasisLMF/OasisLMF/tree/fix/add-calc-rule-for-all-positive-deductibles

The branch contains the deterministic loss generation script. 

Can you please checkout the branch and run FM35 using MDK? I think this should resolve the problem.

**Comment by sr-murthy** [comment]
Fixed in branch, will be merged into `master` via `develop` at some point before the next release.
