### ISSUE TITLE
Min & Max deductibles  at location / spec cond / policy level

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#143]

**Comment by johcarter** [comment]
Fields to support (including limits)
FM Level2: LocDed5PD, LocMinDed5PD, LocMaxDed5PD, LocLimit5PD
FM Level3: LocDed6All, LocMinDed6All, LocMaxDed6All, LocLimit6All
FM Level6: CondDed6All, CondMinDed6All, CondMaxDed6All, CondLimit6All
FM Level9: PolDed6All, PolMinDed6All, PolMaxDed6All, PolLimit6All

**Comment by sr-murthy** [comment]
@johcarter Are there are coverage type filters applied when processing `LocMinDed5PD` and/or `LocMaxDed5PD`?

**Comment by sr-murthy** [comment]
FM41
	====

	acc
	---
	PortNumber,AccNumber,PolNumber,PolPerilsCovered,AccCurrency,PolPeril,PolDedCode6All,PolDedType6All,PolDed6All,PolMinDed6All,PolMaxDed6All,PolLimitCode6All,PolLimitType6All,PolLimit6All,LayerParticipation,LayerLimit,LayerAttachment,CondNumber,CondName,CondPeril,CondDedCode6All,CondDedType6All,CondDed6All,CondMinDed6All,CondMaxDed6All,CondLimitCode6All,CondLimitType6All,CondLimit6All
	1,1,1,QQ1;WW1,USD,QQ1;WW1,0,0,0,0,0,0,0,1500000,1,0,0,1,1,WW1,0,0,0,50000,0,0,0,250000


	loc
	---
	PortNumber,AccNumber,LocNumber,CountryCode,LocPerilsCovered,BuildingTIV,OtherTIV,ContentsTIV,BITIV,LocCurrency,LocPeril,LocDedCode1Building,LocDedType1Building,LocDed1Building,LocMinDed1Building,LocMaxDed1Building,LocDedCode2Other,LocDedType2Other,LocDed2Other,LocMinDed2Other,LocMaxDed2Other,LocDedCode3Contents,LocDedType3Contents,LocDed3Contents,LocDed3ContentsMin,LocMaxDed3Contents,LocDedCode4BI,LocDedType4BI,LocDed4BI,LocMinDed4BI,LocMaxDed4BI,LocDedCode5PD,LocDedType5PD,LocDed5PD,LocMinDed5PD,LocMaxDed5PD,LocDedCode6All,LocDedType6All,LocDed6All,LocMinDed6All,LocMaxDed6All,LocLimitCode1Building,LocLimitType1Building,LocLimit1Building,LocLimitCode2Other,LocLimitType2Other,LocLimit2Other,LocLimitCode3Contents,LocLimitType3Contents,LocLimit3Contents,LocLimitCode4BI,LocLimitType4BI,LocLimit4BI,LocLimitCode5PD,LocLimitType5PD,LocLimit5PD,LocLimitCode6All,LocLimitType6All,LocLimit6All,CondNumber,CondPriority
	1,1,1,US,QQ1;WW1,1000000,0,0,0,USD,QQ1;WW1,0,0,10000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
	1,1,2,US,QQ1;WW1,1000000,0,0,0,USD,QQ1;WW1,0,2,0.01,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
	1,1,3,US,QQ1;WW1,1000000,0,0,0,USD,QQ1;WW1,0,1,0.05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,
	1,1,4,US,QQ1;WW1,2000000,0,0,0,USD,QQ1;WW1,0,0,15000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,
	1,1,5,US,QQ1;WW1,2000000,0,0,0,USD,QQ1;WW1,0,0,10000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,
	1,1,6,US,QQ1;WW1,2000000,0,0,0,USD,QQ1;WW1,0,2,0.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,,

	keys
	----
	LocID,PerilID,CoverageTypeID,AreaPerilID,VulnerabilityID
	1,1,1,1,1
	1,1,2,2,2
	1,1,3,3,3
	1,1,4,4,4
	2,1,1,5,5
	2,1,2,6,6
	2,1,3,7,7
	2,1,4,8,8
	3,1,1,9,9
	3,1,2,10,10
	3,1,3,11,11
	3,1,4,12,12
	4,1,1,13,13
	4,1,2,14,14
	4,1,3,15,15
	4,1,4,16,16
	5,1,1,17,17
	5,1,2,18,18
	5,1,3,19,19
	5,1,4,20,20
	6,1,1,21,21
	6,1,2,22,22
	6,1,3,23,23
	6,1,4,24,24

	items.csv
	---------
	item_id,coverage_id,areaperil_id,vulnerability_id,group_id
	1,1,1,1,1
	2,2,5,5,2
	3,3,9,9,3
	4,4,13,13,4
	5,5,17,17,5
	6,6,21,21,6

	coverages.csv
	-------------
	coverage_id,tiv
	1,1000000.0
	2,1000000.0
	3,1000000.0
	4,2000000.0
	5,2000000.0
	6,2000000.0

	gulsummaryxref.csv
	------------------
	coverage_id,summary_id,summaryset_id
	1,1,1
	2,1,1
	3,1,1
	4,1,1
	5,1,1
	6,1,1

	fm_programme.csv
	----------------
	from_agg_id,level_id,to_agg_id
	1,1,1
	2,1,2
	3,1,3
	4,1,4
	5,1,5
	6,1,6
	1,2,1
	2,2,1
	3,2,1
	4,2,2
	5,2,2
	6,2,2
	1,3,1
	2,3,1
	1,4,1

	fm_profile.csv
	--------------
	policytc_id,calcrule_id,deductible1,deductible2,deductible3,attachment1,limit1,share1,share2,share3
	1,12,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
	2,12,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
	3,12,15000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
	4,12,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
	5,8,0.0,50000.0,0.0,0.0,250000.0,0.0,0.0,0.0
	6,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
	7,14,0.0,0.0,0.0,0.0,1500000.0,0.0,0.0,0.0
	8,2,0.0,0.0,0.0,0.0,9999999999.0,1.0,0.0,0.0

	fm_policytc.csv
	---------------
	layer_id,level_id,agg_id,policytc_id
	1,1,1,1
	1,1,2,1
	1,1,3,2
	1,1,4,3
	1,1,5,1
	1,1,6,4
	1,2,1,5
	1,2,2,6
	1,3,1,7
	1,4,1,8

	fm_xref.csv
	-----------
	output,agg_id,layer_id
	1,1,1
	2,2,1
	3,3,1
	4,4,1
	5,5,1
	6,6,1

	fmsummaryxref.csv
	-----------------
	output,summary_id,summaryset_id
	1,1,1
	2,1,1
	3,1,1
	4,1,1
	5,1,1
	6,1,1

	Ground-up losses (loss_factor=1.0; net=False)
	+------------+-----------+------------+
	|   event_id |   item_id |       loss |
	|------------+-----------+------------|
	|          1 |         1 | 1000000.00 |
	|          1 |         2 | 1000000.00 |
	|          1 |         3 | 1000000.00 |
	|          1 |         4 | 2000000.00 |
	|          1 |         5 | 2000000.00 |
	|          1 |         6 | 2000000.00 |
	+------------+-----------+------------+

	Direct insured losses (loss_factor=1.0; net=False)
	+------------+-------------+-----------+
	|   event_id |   output_id |      loss |
	|------------+-------------+-----------|
	|          1 |           1 |  21030.12 |
	|          1 |           2 |  21030.12 |
	|          1 |           3 |  20180.42 |
	|          1 |           4 | 494190.88 |
	|          1 |           5 | 495435.75 |
	|          1 |           6 | 448132.75 |
	+------------+-------------+-----------+

**Comment by johcarter** [comment]
to test

**Comment by sr-murthy** [comment]
@johcarter Can I close this issue - what is the status of your testing? FM41 does pass.

**Comment by johcarter** [comment]
fm12 also passes so yes we can close
