### ISSUE TITLE
Outputs Reinsurance: RI contract level output (by ReinsNumber and or ReinsType)

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#146]
member request

**Comment by johcarter** [comment]
From the FM subgroup 2 (ppt attached) it seems the important perspectives are 

- Ground up (GU)
- Gross (GR)
- Net of all reinsurance (RI)
- Reinsurance loss (new) 
- Net loss Pre-Cat (new)  

**Reinsurance loss**

This is the loss to the reinsurance contracts. it can be extracted by running the existing reinsurance calculations (iterations of fmpy using the RI_{n} subfolders of input and outputting the gross losses - which means do not use the fmpy -n flag).  
If reinsurance loss is selected as a perspective in analysis settings, we would have to pass reinsurance gross out of every RI_{n} calculation while continuing to pass net loss to the next RI cycle, so creating a new set of pipes for the reinsurance gross outputs to be fed into summarycalc and the output calculations.

Summary levels for reinsurance loss

The summary levels are generally different from all other perspectives as this represents the loss to the reinsurer, not the primary insurer.  The detailed level required is by contract, which is defined by each unique ReinsNumber in ri info.
A higher level grouping is the sum of loss by reinsurance type (identified by ReinsType in ri info). ReinsType is a straight forward grouping of ReinsNumber.  All loss (sum of all reinsurance contracts) would also be required.

The extra challenge of creating reinsurance loss reports is that they will be output split not only by ktools process number but by reinsurance cycle number.   For instance, for a reinsurance program with 3 reinsurance calculation stages we will have RI_1, RI_2 and RI_3.  There will need to be a new gross stream output from each of RI_1, RI_2, and RI_3, which need to be merged together and summed to get the final reports for the reinsurance loss perspective.

**Net loss Pre-cat**

This is the net loss before ReinsType CXL (& AXL,  which is not supported anyway).

- If ReinsType CXL is not present, it is the same as the existing net loss.
- If ReinsType CXL is present, it is the net loss before the first reinsurance calculation cycles which include CXL types. It is safe to assume that CXL would have inuring priority at least greater than any of the other reinsurance types supported (FAC, SS, QS, PR).
- It is possible but unlikely that CXL would have the same inuring priority as one of the other types. in this case it would be necessary to subdivide the calculation into more stages (more RI_{n}), with the FAC,SS,QS,PR cycles first, and then the CXL after so that the net loss can be redirected to outputs before CXL has been calculated.  
- If Net loss Pre-cat is selected but net loss is not selected in analysis settings, you would not need to calculate net loss and any  CXL calculation cycles can be ignored/not generated.

Summary levels for net-loss pre cat

There are no special summary levels required for net-loss pre cat - it would be similar to existing gu, il, ri loss summary levels.

**Comment by johcarter** [comment]
[Oasis_Nazare_TSG_FM_subgroup2_04102023.pdf](https://github.com/OasisLMF/OasisLMF/files/12817264/Oasis_Nazare_TSG_FM_subgroup2_04102023.pdf)

**Comment by benhayes21** [comment]
separate out net loss pre-cat into a different issue
