### ISSUE TITLE
Reinsurance: filtering for other fields (LOB, CountryCode, Cedant, Producer, ReinsTag)

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#148]

**Comment by johcarter** [comment]
More detail:

Working filters:
PortNumber
PortNumber, AccNumber
PortNumber, AccNumber, PolNumber
PortNumber, AccNumber, LocNumber

To do:
LocGroup
Cedant
Producer
LOB
CountryCode
ReinsTag
Contract dates

The to do fields may all be used individually as filters, independently of PortNumber, AccNumber, LocNumber, PolNumber. LocGroup may be specified without reference to a PortNumber and AccNumber. (This is different to LocNumber which must also have PortNumber and AccNumber specified because LocNumber is not unique to a Portfolio and Account. LocGroup is assumed to be unique across portfolios and accounts)

All scope filter fields may be used in combination. The use of multiple scope fields within a row in ri scope are interpreted as AND logical statements so if say LocGroup and PortNumber was specified, then only the locations with both the LocGroup specified value and the PortNumber specified value would have.

**Comment by johcarter** [comment]
[piwind_scope_test.zip](https://github.com/OasisLMF/OasisLMF/files/5623190/piwind_scope_test.zip)

**Comment by benhayes21** [comment]
merging this in https://github.com/OasisLMF/OasisLMF/issues/698

**Comment by johcarter** [comment]
Older duplicate of #1454
