### ISSUE TITLE
Unstable tests in TOX + py2.7.x 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#152]
Four tests in **tests/exposures/test_manager.py** fail intermittently in in python 2.7.x under tox.
But run fine when using pytest alone. 

**Error Trace:** 
https://pastebin.com/raw/cH2YqDGg

Marking these as skip if python is < 3.6 until stable.

**Comment by sr-murthy** [comment]
This is OK, but assumes that there is a solution which can fix this problem with tox. We saw that there are no problems with the test cases themselves (in `tests/exposures/test_manager.py::LoadFmItems`), they all pass using pytest, which actually handles the test execution.

Maybe a better solution is to remove this test class, as the FM acceptance tests in `tests/exposures/test_fm_acceptance.py` use OED data, and represent a better way of testing FM functionality than the FM tests in the exposure manager tests module.

**Comment by sr-murthy** [comment]
This should now be fixed as I'll shortly be updating `develop` with a modified exposure manager tests module with the old FM items generation test cases removed - as we've now got the more detailed test cases in the new FM acceptance tests module (`tests/exposures/test_fm_acceptance.py`).
