### ISSUE TITLE
Making the MDK easier to use in Windows by changing the location of fifo

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#153]
The MDK runs under the Linux sub-system for Windows but only within the Linux file system. This is because mkfifo (used in oasislmf model run) only works in the linux file system.
Windows users find it easier to work in the windows file system (/mnt/c/Documents etc) because they can use windows tools to browse directories and view files.
If the fifos were created explicitly in the linux file system in /temp rather than in /mkfifo relative to where the command is executed then the model run could be executed from anywhere in the windows file system at the Ubuntu command line. 
Sam is going to experiment with this in a branch.

**Comment by mpinkerton-oasis** [comment]
Okay. @bmatharu had been looking at Windows support more generally. I think this would be good to add next year, as there is a definite requirement for the MDK to run under windows (but not the platform).

**Comment by sambles** [comment]
Made a start but it needs some checking, some of the unittests are failing 
https://github.com/OasisLMF/OasisLMF/tree/feature/windows-fifo

**Comment by johcarter** [comment]
Tested branch in the Windows file system with PiWind using Bash for Windows and it works.

**Comment by sambles** [comment]
fixed and merged
