### ISSUE TITLE
Very high memory usage when running both ground-up and gross PLTs

### ISSUE THREAD

**Issue by nicksamps** [OasisLMF/OasisLMF#1543]
## Issue Description
Analyses of even very small location files use surprisingly large amounts of memory (example: 100 locations + 10k years + 8 samples uses > 110gb memory) when running **both** ground-up and gross PLTs. Running with either ground-up OR gross PLT is fine.

## Steps to Reproduce (Bugs only)
1. Run an analysis for **both** ground-up and gross PLTs
2. Watch memory usage

## Version / Environment information

Ubuntu 24.04 LTS
OasisLMF 2.3.5

## Example data / logs

[plt_memory_acc.csv](https://github.com/user-attachments/files/16428276/plt_memory_acc.csv)
[plt_memory_loc.csv](https://github.com/user-attachments/files/16428279/plt_memory_loc.csv)
[plt_analysis_settings.json](https://github.com/user-attachments/files/16428281/plt_analysis_settings.json)
<img width="628" alt="Screenshot 2024-07-30 at 13 52 51" src="https://github.com/user-attachments/assets/b0b142dd-36b5-441f-8944-1eb754e3e694">

**Comment by benhayes21** [comment]
@ncerutti - suggest you pick this up with the rewrite of plt/aal/lec calc

**Comment by benhayes21** [comment]
Closing - to be handled in #1528
