### ISSUE TITLE
dynamic footprint - slow performance for large hazard case

### ISSUE THREAD

**Issue by siobhancampbell** [OasisLMF/OasisLMF#1544]
## Issue Description

The dynamic footprint generation is very slow for larger hazard case files (10s of MB per partition). The following changes should help (~8x faster in local testing):
- vectorize intensity interpolation
- filter the hazard case table for areaperil_id's in exposure

## Version / Environment information

2.3.6+

**Comment by benhayes21** [comment]
Thanks @siobhancampbell - I'll add in those suggestions!
