### ISSUE TITLE
Running full_correlation + gulmc causes an execution to hang.  

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1547]
## Issue Description
An older feature designed for gulcalc called `full_correlation` can be set in the analyses_settings file. If this is combined with `gulmc` (now the default) instead of gulcalc, then the bash `run_ktools.sh` will hang indefinitely.

**analyses_settings.json**
```
{
   "full_correlation": true,
     ...
```
**oasislmf.json**
```
{
      "modelpy": false,
      "gulpy": false,
      "gulmc": true,     
        ...
```

### Cause 
There is a named pipe expediting output to `/tmp/{tmp}/fifo/full_correlation/gul_fc_P{n}` which never receives data, so the script hangs.

**Comment by johcarter** [comment]
@sambles could the fix be to ignore full_correlation flag if gulmc is ran (ie not try to pass the -j parameter into gen bash ) and to proceed with the analysis, please?

**Comment by benhayes21** [comment]
issue is to catch the scenario and set full correlation to false with logs
