### ISSUE TITLE
oasislmf code uses legacy correlation settings location in model settings

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#1581]
## Issue Description
The correlation settings in the model settings schema has recently moved from the root to with the model settings area, but the oasislmf code still looks at the legacy location for the settings.

https://github.com/OasisLMF/OasisLMF/blob/d7790ac5d61781c0817a81e094b3dce7c9b41869/oasislmf/preparation/correlations.py#L21](https://urldefense.com/v3/__https:/github.com/OasisLMF/OasisLMF/blob/d7790ac5d61781c0817a81e094b3dce7c9b41869/oasislmf/preparation/correlations.py*L21

The following maybe would make more sense:

correlation_settings = data.get("model_settings", {}).get("correlation_settings", data.get("correlation_settings",[]))

**Comment by fl-ndaq** [comment]
A second change is apparently needed in https://github.com/OasisLMF/OasisLMF/blob/73d157bf4053fb3eac9587b6deb0e299a63f1775/oasislmf/utils/data.py#L264

correlations: Optional[List[dict]] = model_settings.get("model_settings", {}).get("correlation_settings", model_settings.get("correlation_settings",[]))
