### ISSUE TITLE
Implement single level special condition in MDK

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#159]
fm41 ready to test

**Comment by johcarter** [comment]
[fm41.zip](https://github.com/OasisLMF/OasisLMF/files/2680445/fm41.zip)

**Comment by johcarter** [comment]
Could we use the following fields for the first version of special conditions
CondMinDed6All
CondLimit6All
The calcrules to use are ;
both = 8
ded only = 11
limit only = 14

**Comment by sr-murthy** [comment]
Sounds OK - adding support for additional fields is not that difficult, but it does involve adding those fields to the canonical profiles with the appropriate term structure, and then using that in FM component of the exposure manager. We can discuss the details after the RI work.

**Comment by johcarter** [comment]
to test

**Comment by sr-murthy** [comment]
How will you test this? I assume you will do a `pip install` of the current `develop` branch in your virtual env. (Py 3.6 minimum required)

    pip uninstall -y oasislmf && pip install -v git+{https,ssh}://git@github.com/OasisLMF/OasisLMF.git@develop#egg=oasislmf

and then use the `exposure run` command I've implemented

    $ oasislmf exposure run -i /path/to/test/case/folder [-o /optional/path/to/test/case/outputs/folder]

For FM41 you should see the following output on the console (the files will be re-generated in the test case folder every time you run the command)

	Processing arguments

	Running deterministic losses (GUL=True, IL=True, RI=False)
	STARTED: oasislmf.manager.__init__
	COMPLETED: oasislmf.manager.__init__ in 0.0s
	STARTED: oasislmf.manager.run_deterministic
	STARTED: oasislmf.manager.generate_oasis_files
	STARTED: oasislmf.model_preparation.gul_inputs.get_gul_input_items
	COMPLETED: oasislmf.model_preparation.gul_inputs.get_gul_input_items in 0.41s
	STARTED: oasislmf.model_preparation.gul_inputs.write_gul_input_files
	STARTED: oasislmf.model_preparation.gul_inputs.write_items_file
	STARTED: oasislmf.model_preparation.gul_inputs.write_coverages_file
	COMPLETED: oasislmf.model_preparation.gul_inputs.write_items_file in 0.04s
	STARTED: oasislmf.model_preparation.gul_inputs.write_gulsummaryxref_file
	COMPLETED: oasislmf.model_preparation.gul_inputs.write_coverages_file in 0.05s
	COMPLETED: oasislmf.model_preparation.gul_inputs.write_gulsummaryxref_file in 0.01s
	COMPLETED: oasislmf.model_preparation.gul_inputs.write_gul_input_files in 0.16s
	STARTED: oasislmf.model_preparation.il_inputs.get_il_input_items
	COMPLETED: oasislmf.model_preparation.il_inputs.get_il_input_items in 0.33s
	STARTED: oasislmf.model_preparation.il_inputs.write_il_input_files
	STARTED: oasislmf.model_preparation.il_inputs.write_fm_policytc_file
	STARTED: oasislmf.model_preparation.il_inputs.write_fm_profile_file
	COMPLETED: oasislmf.model_preparation.il_inputs.write_fm_profile_file in 0.06s
	STARTED: oasislmf.model_preparation.il_inputs.write_fm_programme_file
	COMPLETED: oasislmf.model_preparation.il_inputs.write_fm_policytc_file in 0.12s
	STARTED: oasislmf.model_preparation.il_inputs.write_fm_xref_file
	COMPLETED: oasislmf.model_preparation.il_inputs.write_fm_programme_file in 0.04s
	STARTED: oasislmf.model_preparation.il_inputs.write_fmsummaryxref_file
	COMPLETED: oasislmf.model_preparation.il_inputs.write_fm_xref_file in 0.09s
	COMPLETED: oasislmf.model_preparation.il_inputs.write_fmsummaryxref_file in 0.01s
	COMPLETED: oasislmf.model_preparation.il_inputs.write_il_input_files in 0.81s
	COMPLETED: oasislmf.manager.generate_oasis_files in 2.2s
	STARTED: oasislmf.manager.generate_deterministic_losses
	STARTED: oasislmf.model_execution.bin.csv_to_bin
	COMPLETED: oasislmf.model_execution.bin.csv_to_bin in 0.12s

	Generating deterministic ground-up and direct insured losses with command: gultobin -S 1 < /Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/validation/data/fm41/guls.csv | fmcalc -p /Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/validation/data/fm41  -a 2 | tee ils.bin | fmtocsv > /Users/srm/Documents/sandeep/cst/dev/oasis/OasisLMF/validation/data/fm41/ils.csv

	COMPLETED: oasislmf.manager.generate_deterministic_losses in 0.19s
	COMPLETED: oasislmf.manager.run_deterministic in 2.39s

	Ground-up losses (loss_factor=1.0; net=False)
	+------------+-----------+------------+
	|   event_id |   item_id |       loss |
	|------------+-----------+------------|
	|          1 |         1 | 1000000.00 |
	|          1 |         2 | 1000000.00 |
	|          1 |         3 | 1000000.00 |
	|          1 |         4 | 2000000.00 |
	|          1 |         5 | 2000000.00 |
	|          1 |         6 | 2000000.00 |
	+------------+-----------+------------+

	Direct insured losses (loss_factor=1.0; net=False)
	+------------+-------------+-----------+
	|   event_id |   output_id |      loss |
	|------------+-------------+-----------|
	|          1 |           1 |  21030.12 |
	|          1 |           2 |  21030.12 |
	|          1 |           3 |  20180.42 |
	|          1 |           4 | 494190.88 |
	|          1 |           5 | 495435.75 |
	|          1 |           6 | 448132.75 |
	+------------+-------------+-----------+

**Comment by sr-murthy** [comment]
@johcarter Same for this issue - can it be closed?

**Comment by johcarter** [comment]
fm12 complete
