### ISSUE TITLE
mkfifo does not work properly in msys2

### ISSUE THREAD

**Issue by monellid** [OasisLMF/OasisLMF#171]
I installed oasismlf in windows using msys2 but I'm having issues in running the 'run_ktools.sh' script. I traced back the error to the 'mkfifo' command which does not seem to properly work (see https://github.com/Alexpux/MSYS2-packages/issues/1333). How could the 'run_ktools.sh' script be modified to run under msys2?

**Comment by johcarter** [comment]
We think we know the solution to this, please see #153
For now, if you would like to use the oasislmf package in Windows you can install the Linux subsystem for Windows (available in Windows 10) and run in the Linux file system.
