### ISSUE TITLE
Flamingo Server - Loss Threshold does not allow decimal values

### ISSUE THREAD

**Issue by jonathanbethel** [OasisLMF/OasisLMF#183]
This is linked to an idea from that the Loss Threshold value was causing performance issues. I have enabled decimal inputs in Modex, but Flamingo Server doesn't actually support this as a value. It expects an int (in both the SQL DB and Flamingo Server). @benhayes21 suggested Loss Threshold should be allowed to take a decimal value more generally.

Also should be integrated into the new API (if it hasn't been already), where decimal values for Loss Threshold should be allowed.

**Comment by benhayes21** [comment]
This is a database issue. Solution is to update the workflowflattener stored procedure to set the @GULThreshold parameter to a float and also update the parameter table to set parameterformat = 'float' where parameterid = 6
