### ISSUE TITLE
api_client - Add interface for pandas Dataframes 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#212]

**Comment by mpinkerton-oasis** [comment]
This would be a useful enchancement for calling the API from analtytic Python code, Jupiter notebooks etc.

**Comment by sambles** [comment]
Added in #334

All file endpoints have access to the `to_dataframes()` method. It works for Tar and single csv files:

**Examples:**
``
from oasislmf.api.client import *
session = APIClient('http://99.80.10.98:8000/', 'v1', 'admin', 'password')

loc_file = session.portfolios.location_file.to_dataframes(1)
inputs_csv = session.analyses.input_file.to_dataframes(1)
output_csv = session.analyses.output_file.to_dataframes(1)
```

```
In [15]: loc_file.keys()                                                                                  
Out[15]: dict_keys(['location_file'])
In [16]: type(loc_file['location_file'])                                                                  
Out[16]: pandas.core.frame.DataFrame
```


```
dict_keys(['fm_xref.csv', 'reinsscope.csv', 'fm_summary_map.csv', 'account.csv', 'keys.csv', 'fm_programme.csv', 'fm_policytc.csv', 'location.csv', 'fm_profile.csv', 'keys-errors.csv', 'coverages.csv', 'reinsinfo.csv', 'gul_summary_map.csv', 'items.csv'])
```

```
In [11]: output_csv.keys()                                                                                
Out[11]: dict_keys(['gul_S1_leccalc_full_uncertainty_oep.csv', 'gul_S1_eltcalc.csv', 'gul_S1_leccalc_full_uncertainty_aep.csv', 'gul_S1_aalcalc.csv'])
```
