### ISSUE TITLE
Endianness of packed data for complex models

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#213]
For the complex model, the model data in the item file is packed binary data. The endianness is not explicitly set, so picks the system default. This is fine if everything is on the same base OS, but could conceivably cause issues on a mixed OS installation in future. Suggest to explicitly set endienness.

**Comment by sambles** [comment]
Closing for the moment - Should be find assuming the workers are homogeneous.  If it becomes and issue will investigate
