### ISSUE TITLE
Handling duplicate location rows in OED

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#221]
LocNumber is the primary identified of a location in the OED location file but a location can have duplicate records where there are multiple special conditions (different values in CondNumber and CondPriority fields) or multiple financial terms applying to different perils (different values in LocPeril field).

Duplicate rows should be handled before sending locations to the key server to ensure that a location is not modelled for ground up loss more than once.

The set of fields which uniquely identify a location (which can be used to create an internal unique location id for the purposes of reporting) are;

LocNumber
CountryCode
LocPerilsCovered
BuildingTIV
OtherTIV
ContentsTIV
BITIV
LocCurrency
PortNumber
AccNumber

FYI @sambles @sr-murthy 
@mpinkerton-oasis to triage

**Comment by johcarter** [comment]
@mpinkerton-oasis  This came up during a conversation with Sam. The oasis file generation assumption downstream from key server is that the locnumber returned is unique.

**Comment by mpinkerton-oasis** [comment]
This has been addressed.
