### ISSUE TITLE
generate_summaryxref_files function ignores "il_output" setting

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#272]
I have a config file in which the following settings exist:
```
        "il_output": false,
        "il_summaries": [
            {
                "aalcalc": true,
                "eltcalc": true,
                "id": 1,
                "lec_output": true,
                "leccalc": {
                    "outputs": {
                        "full_uncertainty_aep": true,
                        "full_uncertainty_oep": true
                    },
                    "return_period_file": true
                }
            }
        ],
```

As `il_output` is False and I am not providing an accounts file, I do not expect OasisLMF to be looking for any insured-loss-related inputs. However, when attempting to run an analysis, OasisLMF is still searching for the FM summary map file (which OasisLMF is not generating, due to no accounts file) in `oasislmf.model_preparation.summaries.generate_summaryxref_files`, because it only checks whether the `il_summaries` setting exists, ignoring `il_output`.

**Comment by sr-murthy** [comment]
The summaries implementation was recently done by @sambles, so best to ask him - he is away on leave for the next two weeks. But this feature is not yet part of any release, so technically this issue isn't a release issue. I will close this issue, but take note of your suggestion.

I can see that the summary xref files are generated based on checking for the existence of the corresponding `_summaries` key in analysis settings, not on the output key. It would easy enough to change this.

Also, the GUL and FM summary maps are generated unconditionally. You would have to ask @sambles about this.

**Comment by DanielFEvans** [comment]
Where would you like in-development issues like this to be highlighted? Slack is one option, but things tend to get lost very quickly on there.

**Comment by sr-murthy** [comment]
You are free to highlight posts in the JBA Slack channels.

Normally, GitHub issues should be created to highlight issues which pertain to a feature or bug in an existing release, or to request a proposed feature or fix. The summaries feature is still in development.
