### ISSUE TITLE
Validation picks up wrong location files

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#276]
When running the exposure validation tests, the wrong exposure files can be picked up. For example, if the file is being edited and a lock files created (" .~lock.location.csv#" for example) then this gets picked up.

**Comment by sr-murthy** [comment]
@mpinkerton-oasis The source file paths are parsed in the command class (`cli.exposure.RunCmd`), but are actually loaded in the command handler in the manager (`manager.OasisManager.run_deterministic`). I've made some changes to require that the location file must be named `location.csv`, the account file must be named `account.csv`, and the RI info. and scope files must be named `ri_info.csv` and `ri_scope.csv`. This should exclude the lock file versions of these from being accidentally processed instead.

**Comment by sr-murthy** [comment]
Tested and fixed
