### ISSUE TITLE
Reinsurance: Implement risk limits for CXL

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#289]
Occasionally, Catastrophe excess of loss treaties can have risk level terms (ceded %, risk attach, risklimit).

**Comment by benhayes21** [comment]
https://github.com/OasisLMF/OasisLMF/issues/721

**Comment by johcarter** [comment]
There is no known business case for a CXL with risk terms. Any unusual contracts with risk terms could be coded as a Per Risk. 
We will add support for Occurrence Attachment for a Per Risk, so that all terms are supported and this ReinsType can be used as a catch all for reinsurance with special features.

**Comment by johcarter** [comment]
Replaced by https://github.com/OasisLMF/OasisLMF/issues/1515
