### ISSUE TITLE
Reinsurance: issue with ri_single_pol_level_fac

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#291]
It seems that location losses are being merged together, possibly because they share a common policy num over different accounts. feature/ri_updates branch

here are the four locations. both accounts have PolNumber = 1

PortNumber,AccNumber,LocNumber,LocGroup,CountryCode,AreaCode,LocPerilsCovered,BuildingTIV,OtherTIV,ContentsTIV,BITIV,LocCurrency,CondNumber,CondPriority,LocDedType1Building,LocDed1Building,LocDedType2Other,LocDed2Other,LocDedType3Contents,LocDed3Contents,LocDedType4BI,LocDed4BI,LocDedType5PD,LocDed5PD,LocMinDed5PD,LocMaxDed5PD,LocDedType6All,LocDed6All,LocMinDed6All,LocMaxDed6All,LocLimitType1Building,LocLimit1Building,LocLimitType2Other,LocLimit2Other,LocLimitType3Contents,LocLimit3Contents,LocLimitType4BI,LocLimit4BI,LocLimitType5PD,LocLimit5PD,LocLimitType6All,LocLimit6All,PortNumber
1,1,1,0,US,CA,0,1000,0,500,500,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1
1,1,2,0,US,CA,0,1000,0,500,500,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1
1,2,1,0,US,CA,0,1000,0,500,500,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1
1,2,2,0,US,CA,0,1000,0,500,500,0,,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,1

But the loss for account 2, location 1 and account 1 location 2 are being merged together;

Losses (loss factor=1.0; total gul=16,000; total il=200; total ri ceded=10)
+--------------+-------------+-------------+------------+-----------+-----------+
|   portnumber |   accnumber |   locnumber |   loss_gul |   loss_il |   loss_ri |
|--------------+-------------+-------------+------------+-----------+-----------|
|            1 |           1 |           1 |    4000.00 |     50.00 |     44.98 |
|            1 |           1 |           2 |    8000.00 |    100.00 |     94.98 |
|            1 |           2 |           2 |    4000.00 |     50.00 |     50.00 |
+--------------+-------------+-------------+------------+-----------+-----------+

**Comment by mpinkerton-oasis** [comment]
Old issue
