### ISSUE TITLE
FM tests

### ISSUE THREAD

**Issue by sr-murthy** [OasisLMF/OasisLMF#317]
@johcarter I've merged in the branch to refactor the FM tests to use the exposure validation command. When the test suite is run, either manually or in a CI build, all of the FM test cases in `validation/examples` with expected data are automatically run. 

These are the passing FM test cases currently on this branch

	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX29_03
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX29_05
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX29_08
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX30_03
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX30_05
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA37_02
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm3
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm4
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm40
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm41
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm5
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm6
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm7
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm8
	PASSED tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm9

All the tests below however appear to be failing (due to layer IDs not matching in some of the FM files), but it may be that we need to update the expected data files for these test cases, because in recent work we've actually corrected the way layer IDs are generated (to generate them as index IDs on policy numbers within portfolio num. & account. num. combinations). So for the moment I've skipped these. Perhaps if you could take a look at FM12 (the files I sent you in Slack) that could indicate what is happening with the layer IDs, which might be the same in the other test cases.

	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX29_95 SKIPPED [  5%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX30_100 SKIPPED [  9%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX30_97 SKIPPED [ 10%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX31_102 SKIPPED [ 12%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX31_104 SKIPPED [ 13%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX32_107 SKIPPED [ 14%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_CX32_108 SKIPPED [ 16%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA37_125 SKIPPED [ 18%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA38_129 SKIPPED [ 20%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA39_133 SKIPPED [ 21%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA40_134 SKIPPED [ 22%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA41_138 SKIPPED [ 24%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA42_142 SKIPPED [ 25%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA43_143 SKIPPED [ 27%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_FA44_147 SKIPPED [ 28%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR13_42 SKIPPED [ 29%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR13_44 SKIPPED [ 31%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR14_47 SKIPPED [ 32%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR15_48 SKIPPED [ 33%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR16_52 SKIPPED [ 35%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR17_56 SKIPPED [ 36%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR17_57 SKIPPED [ 37%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR18_58 SKIPPED [ 39%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR19_62 SKIPPED [ 40%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR20_66 SKIPPED [ 41%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR21_67 SKIPPED [ 43%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR22_72 SKIPPED [ 44%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR23_76 SKIPPED [ 45%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR24_77 SKIPPED [ 47%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR25_81 SKIPPED [ 48%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR25_83 SKIPPED [ 50%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR26_86 SKIPPED [ 51%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR27_87 SKIPPED [ 52%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_PR28_91 SKIPPED [ 54%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS05_15 SKIPPED [ 55%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS05_16 SKIPPED [ 56%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS06_17 SKIPPED [ 58%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS07_21 SKIPPED [ 59%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS08_26 SKIPPED [ 60%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS09_27 SKIPPED [ 62%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS09_30 SKIPPED [ 63%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS10_32 SKIPPED [ 64%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS11_36 SKIPPED [ 66%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS11_37 SKIPPED [ 67%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_QS12_38 SKIPPED [ 68%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_SS01_2 SKIPPED [ 70%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_SS02_6 SKIPPED [ 71%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_SS03_7 SKIPPED [ 72%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_SS04_11 SKIPPED [ 74%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_fm12 SKIPPED [ 75%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_different_inuring_levels SKIPPED [ 89%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_same_inuring_level SKIPPED [ 90%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS SKIPPED [ 91%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS_with_location_level_risk_limits SKIPPED [ 93%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_cxl SKIPPED [ 94%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_all_risks SKIPPED [ 95%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_loc_filter SKIPPED [ 97%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_fac SKIPPED [ 98%]
	tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_pol_level_fac SKIPPED [100%]

**Comment by sr-murthy** [comment]
@johcarter What is the status of checking the newly generated FM12 input files? ATM this test case is skipped from the test suite because of inconsistencies between the old set of expected files and the newly generated ones (after the changes in layer ID and loc. generation).

**Comment by johcarter** [comment]
fm12 is complete. Waiting for https://github.com/OasisLMF/OasisLMF/issues/347 to be done before looking at the others.

**Comment by johcarter** [comment]
These are still todo
ests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_different_inuring_levels SKIPPED [ 89%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_same_inuring_level SKIPPED [ 90%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS SKIPPED [ 91%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS_with_location_level_risk_limits SKIPPED [ 93%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_cxl SKIPPED [ 94%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_all_risks SKIPPED [ 95%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_loc_filter SKIPPED [ 97%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_fac SKIPPED [ 98%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_pol_level_fac SKIPPED [100%
