### ISSUE TITLE
% TIV terms (DedType=2) change in logic

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#331]
% TIV terms should apply to the sum of TIV of the locations under the policy. If entered as a percentage then fmcalc will apply the percentage to the sum of TIV of impacted locations, which may be fewer.

So whenever we have a Type 2 deductible, we need to convert it to an amount to go in the fm_profile table, and apply the suitable calcrule.

Here are the affected cases (see oed_transformation_spec)
![image](https://user-images.githubusercontent.com/11421733/60733240-35294380-9f44-11e9-9a5d-938361653748.png)

The deductible1 should be the percentage value in the OED ded field, multiplied by the total TIV of the relevant coverages or locations.

**Comment by johcarter** [comment]
@sr-murthy i think this has been done. do you agree?

**Comment by sr-murthy** [comment]
@johcarter This was done about 3 weeks ago. This is the commit, and you can see the change to apply the conversion rule for type 2 deductibles using a TIV aggregate based on locations with the same agg. ID

**Comment by sr-murthy** [comment]
https://github.com/OasisLMF/OasisLMF/commit/0c558ac67740e76dfb4f79dd1ac26b00b0c35ceb
