### ISSUE TITLE
Display error in guls using -o output options

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#344]
The ground up losses by policy are displayed wrong, but the total and raw values are correct.
See loss_gul column, which should sum to 900m

test: SS01_2

Now (develop latest):
Losses (loss factor=1.0; total gul=900,000,000; total il=596,000,042; total ri ceded=79,400,000)
+--------------+-------------+-------------+--------------+--------------+--------------+
| portnumber   | accnumber   | polnumber   |     loss_gul |      loss_il |      loss_ri |
|--------------+-------------+-------------+--------------+--------------+--------------|
| OEDTest      | SS01_03     | SS01_03_1   | 100000000.00 |   2000000.25 |   1800000.27 |
| OEDTest      | SS01_04     | SS01_04_1   | 100000000.00 | 198000002.00 | 198000002.00 |
| OEDTest      | SS01_07     | SS01_07_1   | 100000000.00 | 396000040.00 | 316800040.00 |
+--------------+-------------+-------------+--------------+--------------+--------------+

Before (develop tag 1.3.10 5th June 2019)

Losses (loss factor=1.0; total gul=900,000,000; total il=596,000,042; total ri ceded=79,400,000)
+--------------+-------------+-------------+--------------+--------------+--------------+
| portnumber   | accnumber   | polnumber   |     loss_gul |      loss_il |      loss_ri |
|--------------+-------------+-------------+--------------+--------------+--------------|
| OEDTest      | SS01_03     | SS01_03_1   | 300000000.00 |   2000000.25 |   1800000.27 |
| OEDTest      | SS01_04     | SS01_04_1   | 200000000.00 | 198000002.00 | 198000002.00 |
| OEDTest      | SS01_07     | SS01_07_1   | 400000000.00 | 396000040.00 | 316800040.00 |
+--------------+-------------+-------------+--------------+--------------+--------------+

to replicate:
$ oasislmf exposure run -s /validation/examples/SS01_2 -o pol

**Comment by mpinkerton-oasis** [comment]
Fixed in branch feature/fmtest_outputs_fix

**Comment by sr-murthy** [comment]
PR has been merged into `develop`

https://github.com/OasisLMF/OasisLMF/pull/351
