### ISSUE TITLE
FM tests: create script to automatically update expected results

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#348]

**Comment by johcarter** [comment]
feature/update-test-case-script ready to merge

**Comment by sr-murthy** [comment]
Yes, the PR was created from the branch earlier and passed all the tests, but `develop` has been updated since then. I'm just waiting for the updated PR to pass the tests again in CI.

**Comment by sr-murthy** [comment]
@johcarter Merged. I'm guessing the issue can be closed.
