### ISSUE TITLE
Should the analysis_settings.json field "oed_fields" be mandatory 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#349]
In previous versions of the OED column picker field didn't exist so when implement the OED field selection was seen as optional. 

The next release intends to use this more extensively:
```
This field allows the UI to map between the id (e.g. "S1") and the actual summary level  it corresponded to (e.g. "Portfolio"). 
```

Should a default be added if missing? or an error thrown

**Comment by johcarter** [comment]
note this is different to Portfolio which should use PortNumber as a key

**Comment by sambles** [comment]
The current fallback behavior is, set the summary_set = 1 with no meaning attached and the info files look like:

**gul_S1_summary-info.csv**
```
summary_id,n/a                                                                                                                                                                                                      
1,undefined
```
