### ISSUE TITLE
fm files layer_id and agg_id logic errors

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#352]
layer_id (the value that is written to fm_policytc) seems to increment on the basis of each distinct portfolio, account and policy, whereas it should only increment for multiple policies within each portfolio account.

I attach the fm_summary_map for test case FA45_149, assuming that the layer_id in this file is the same as the value that goes into fm_policytc.  I have included the correct values in the last column as correct_layer_id.
[fm_summary_map.xlsx](https://github.com/OasisLMF/OasisLMF/files/3407245/fm_summary_map.xlsx)

This problem only manifests in results where you have multiple layers per port-account. Many of our test cases are single layer per port-account

The level 3 agg_id grouping is also not right.  This is the Pol6All level where locations are grouped to apply blanket policy terms.  This should actually be a grouping of locations by port-account. You can see this relationship by selecting distinct accnumber, locnumber from the fm_summary_map table, like so;

locnumber | accnumber | loc_id | to_agg_id
-- | -- | -- | --
FA45_01_1 | FA45_01 | 1 | 1
FA45_02_1 | FA45_02 | 2 | 2
FA45_02_2 | FA45_02 | 3 | 2
SS01_04_1 | SS01_04 | 4 | 3
SS01_04_2 | SS01_04 | 5 | 3

I have attached the fm_programme file, with correct to_agg_id in the final column.
[fm_programme.xlsx](https://github.com/OasisLMF/OasisLMF/files/3407247/fm_programme.xlsx)

**Comment by sr-murthy** [comment]
@johcarter can you please repost the FM summary map excel file just as a markdown snippet/table (I don't use Excel and it is hard to work with this file format), and only the portfolio number, acc. number and policy number columns (as layer ID is a function of those three columns only). I don't need the other columns.

**Comment by johcarter** [comment]
[fm_programme.txt](https://github.com/OasisLMF/OasisLMF/files/3407350/fm_programme.txt)
[fm_summary_map.txt](https://github.com/OasisLMF/OasisLMF/files/3407351/fm_summary_map.txt)

**Comment by sr-murthy** [comment]
@johcarter I've made a small change in one of the data utils methods used for layer ID generation. It's in the `fix/data-utils` branch. I'm seeing the correct layer IDs for the level 3 items in the FA49_149 policy TC file.

    layer_id,level_id,agg_id,policytc_id
    ...
    ...
    1,3,1,3
    2,3,1,3
    1,3,2,3
    1,3,3,3
    2,3,3,3

Please test.

The agg. ID requires a separate fix, because I'm still seeing the incorrect values which you've highlighted - as I've mentioned before aggregation is not done directly by the code, but indirectly by reading an aggregation profile JSON, which defines how items in the IL inputs table should be aggregated in each level.

https://github.com/OasisLMF/OasisLMF/blob/fix/data-utils/oasislmf/_data/default_fm_agg_profile.json#L81

I think you must be referrring to FM level 9 (policy all, the `6` is the coverage type ID) - aggregation for this level is done using portfolio and account numbers, but it is possible something is causing the agg. IDs for that level to not be calculated correctly.

**Comment by sr-murthy** [comment]
@johcarter I can't see anything wrong with the agg. ID calculation as the profile is correct for level 9 (policy all) - in fact it appears that the FM terms columns for that level in FA45_149 which are

    ['polded6all', 'polminded6all', 'polmaxded6all', 'pollimit6all', 'poldedcode6all', 'poldedtype6all', 'pollimitcode6all', 'pollimittype6all']

all have 0 values in the accounts file/dataframe, which means level 9 in the IL inputs dataframe has all zero values in these columns, which means the FM terms for this level are all 0 and the level is dropped. I apply a check for each level to exclude any for which the relevant FM terms columns all have 0 values. So that's the problem. Below is the slice of the accounts dataframe for FA45_149.


    ipdb> accounts_df.loc[:, ['polded6all', 'polminded6all', 'polmaxded6all', 'pollimit6all', 'poldedcode6all', 'poldedtype6all', 'pollimitcode6all', 'pollimittype6all']]                                                                                             
       polded6all  polminded6all  polmaxded6all  pollimit6all  poldedcode6all  poldedtype6all  pollimitcode6all  pollimittype6all
    0         0.0            0.0            0.0           0.0               0               0                 0                 0
    1         0.0            0.0            0.0           0.0               0               0                 0                 0
    2         0.0            0.0            0.0           0.0               0               0                 0                 0
    3         0.0            0.0            0.0           0.0               0               0                 0                 0
    4         0.0            0.0            0.0           0.0               0               0                 0                 0

**Comment by sr-murthy** [comment]
@johcarter the Level 3 that you're referring to in FA45_149 is in fact the `site all` level (level 3) - when we process the original sequence of supported FM levels (site coverage #1, site pd #2, site all #3, cond. all #6, policy all #9, policy layer #10) against the items in the dataframe we drop any rows in levels (excluding site coverage and policy layer) with 0 values for all the financial terms in that level. So in FA45_149 it appears the only intermediate level with non-zero financial terms is site all (site all, #3).

        locded6all  locminded6all  locmaxded6all  loclimit6all  locdedcode6all  locdedtype6all  loclimitcode6all  loclimittype6all
    0    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    1    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    2    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    3    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    4    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    5    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    6    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    7    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    8    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    9    1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    10   1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    11   1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    12   1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    13   1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0
    14   1000000.0            0.0            0.0           0.0             0.0             0.0               0.0               0.0

**Comment by johcarter** [comment]
I think Level 3 is Policy Layer 10. however the agg_id grouping should still be based on distinct port-account (same logic as level 9) and the layer_id increments across multiple policies within a port-account.

Will test your layer_id fix - thanks

**Comment by johcarter** [comment]
have tested FA45_149 and the layer_ids look right.  It should be correct when the level 3 to_agg_id is fixed

**Comment by sr-murthy** [comment]
@johcarter Yes level 3 in the file is level 10  - not level 3. But before reindexing the level IDs, level 3 (site all) is the only FM level in the frame with non-zero terms, all other levels (6,9) are zero, therefore dropped. After reindexing level 1 (site coverage) remains level 1, but level 3 (site all) becomes level 2 and level 10 (policy layer) becomes level 3.

Agg. ID are being correctly assigned to level 3 (level 10) items. Here's a table of items in this level using the columns `locnumber`, `loc_id`, `portnumber`, `accnumber`, `agg_id`.

    ipdb> il_inputs_df[il_inputs_df['orig_level_id']==10].loc[:, ['locnumber', 'loc_id'] + agg_key + ['agg_id']].drop_duplicates()    
    locnumber  loc_id     portnumber accnumber  agg_id
    FA45_01_1  1          OEDTest    FA45_01    1
    FA45_02_1  2          OEDTest    FA45_02    2
    FA45_02_2  3          OEDTest    FA45_02    2
    SS01_04_1  4          OEDTest    SS01_04    3
    SS01_04_2  5          OEDTest    SS01_04    3

**Comment by sr-murthy** [comment]
@johcarter loc. numbers don't uniquely identify locations in the loc. file. That is why we are using `loc_id`, a composite index on `portnumber`, `accnumber` and `locnumber`.

**Comment by johcarter** [comment]
yes this looks correct
locnumber  loc_id     portnumber accnumber  agg_id
FA45_01_1  1          OEDTest    FA45_01    1
FA45_02_1  2          OEDTest    FA45_02    2
FA45_02_2  3          OEDTest    FA45_02    2
SS01_04_1  4          OEDTest    SS01_04    3
SS01_04_2  5          OEDTest    SS01_04    3

but in fm_programme we are still getting to_agg_id 1,1,2,2,3 with respect to the order of locations above which is incorrect.

**Comment by sr-murthy** [comment]
It looks if I exclude the layer ID column in the FM policy TC file generation then I'm seeing the correct numbers for agg. ID

    loc_id   level_id  agg_id  policytc_id   orig_level_id
    30       1         3       1             10
    36       2         3       2             10
    39       3         3       2             10
    42       4         3       3             10
    48       5         3       3             10

However including layer ID is throwing out the agg. IDs because some locations are attached to multiple layers - loc. IDs `1` (`FA45_01_1`), `4` (`SS01_04_1`), and `5` (`SS01_04_2`), while others like `3` (`FA45_02_1`) and `4` (`FA45_02_2`) are not.

**Comment by johcarter** [comment]
so the aggregation heirarchy is independent of layers (polnumber). it is about groupings of portnumber, accntnumber, locnumber and condnumber.   Do you know what you need to fix this now?

**Comment by sr-murthy** [comment]
Yes, I realise that now. So I do need to make a small change in the way the columns in the FM programme file are generated, i.e `from_agg_id` and `to_agg_id`. This will take some time, including for testing, but it should be OK.

**Comment by sambles** [comment]
#353

**Comment by johcarter** [comment]
FA45_149
FA45_150
FA45_151

All showing correct results now. loc_summary.csv needs fixing for incorrect displayed guls #369
