### ISSUE TITLE
run_ktools.sh and gulsummaryxref changes for outputs by peril

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#360]
when outputs by subperil are required, the following changes are needed

In run_ktools.sh:
gulcalc:  add parameter -a1 (note this is currently -A1) and remove -c stream
feed gulcalc -i into summarycalc for ground up loss outputs
summarycalc: change -g to -i for the ground up loss outputs

eg
gulcalc -a1 -i - | summarycalc -i ...

Insured loss workflow remains the same except for the new -a1 gulcalc flag

gulcalc -a1 -i - | fmcalc | summarycalc -f ...

gulcalc -c - is completely removed from workflow.

gulsummaryxref.bin
first column changes from coverage_id to item_id
ie item_id, summary_id, summary_set_id

summary id must be generated in relation to item_ids not coverage_ids

From what I understand the condition for the above behaviour is:
peril_id is specified as a field in analysis_settings. 
but i'm not sure.
@benhayes21 @mpinkerton-oasis thoughts please?

**Comment by sambles** [comment]
Note: -a1 == Alloc rule 1 for gulcalc

**Comment by sambles** [comment]
#376

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisPlatform/pull/232
