### ISSUE TITLE
Display error in guls using -o output options (2nd issue)

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#369]
Guls seem to be double counted where there are multiple policy layers, for all output options

The total displayed in the headline is correct.

In example FA45_149, the guls sum to 800m, but the correct total is 500m as in the headline

-o loc 

Losses (loss factor=1.0; total gul=500,000,000; total il=396,000,027; total ri ceded=400,000)
+--------------+-------------+-------------+--------------+-------------+-------------+
| portnumber   | accnumber   | locnumber   |     loss_gul |     loss_il |     loss_ri |
|--------------+-------------+-------------+--------------+-------------+-------------|
| OEDTest      | FA45_01     | FA45_01_1   | 200000000.00 | 99000000.00 | 98800000.00 |
| OEDTest      | FA45_02     | FA45_02_1   | 100000000.00 | 49500004.50 | 49500004.50 |
| OEDTest      | FA45_02     | FA45_02_2   | 100000000.00 | 49500004.50 | 49300004.50 |
| OEDTest      | SS01_04     | SS01_04_1   | 200000000.00 | 99000009.00 | 99000009.00 |
| OEDTest      | SS01_04     | SS01_04_2   | 200000000.00 | 99000009.00 | 99000009.00 |
+--------------+-------------+-------------+--------------+-------------+-------------+

-o pol

Losses (loss factor=1.0; total gul=500,000,000; total il=396,000,027; total ri ceded=400,000)
+--------------+-------------+-------------+--------------+-------------+-------------+
| portnumber   | accnumber   | polnumber   |     loss_gul |     loss_il |     loss_ri |
|--------------+-------------+-------------+--------------+-------------+-------------|
| OEDTest      | FA45_01     | FA45_01_1   | 100000000.00 | 49500000.00 | 49400000.00 |
| OEDTest      | FA45_01     | FA45_01_2   | 100000000.00 | 49500000.00 | 49400000.00 |
| OEDTest      | FA45_02     | FA45_02_1   | 200000000.00 | 99000009.00 | 98800009.00 |
| OEDTest      | SS01_04     | SS01_04_1   | 200000000.00 | 99000009.00 | 99000009.00 |
| OEDTest      | SS01_04     | SS01_04_2   | 200000000.00 | 99000009.00 | 99000009.00 |
+--------------+-------------+-------------+--------------+-------------+-------------+

-o acc

Losses (loss factor=1.0; total gul=500,000,000; total il=396,000,027; total ri ceded=400,000)
+--------------+-------------+--------------+--------------+--------------+
| portnumber   | accnumber   |     loss_gul |      loss_il |      loss_ri |
|--------------+-------------+--------------+--------------+--------------|
| OEDTest      | FA45_01     | 200000000.00 |  99000000.00 |  98800000.00 |
| OEDTest      | FA45_02     | 200000000.00 |  99000009.00 |  98800009.00 |
| OEDTest      | SS01_04     | 400000000.00 | 198000018.00 | 198000018.00 |
+--------------+-------------+--------------+--------------+--------------+

Affects test cases;
FA45_149
FA45_150
FA45_151

These cases are otherwise correct.

**Comment by mpinkerton-oasis** [comment]
I think this is due to double counting across policies.
