### ISSUE TITLE
Set dtypes for exposure data in lookup

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#383]
Amend the code in lookup.py to explicitly set the OED field types. This is specifically to address an issue where some geographic codes have leading 0s and the default Pandas behavior is to drop the 0s and cast them as numbers, causing the lookup to fail.

This is the list of all loc. file columns (OED) which in the OED schema are defined to be “string” columns
```[
    "AccNumber (Loc)",
    "AreaCode (Loc)",
    "AreaName (Loc)",
    "BuildingValuation (Loc)",
    "City (Loc)",
    "CompletionDate (Loc)",
    "CountryCode (Loc)",
    "CustomFloodZone (Loc)",
    "Datum (Loc)",
    "FlexiLocZZZ (Loc)",
    "FloodZone (Loc)",
    "FloorsOccupied (Loc)",
    "Geocoder (Loc)",
    "GeogName1 (Loc)",
    "GeogName2 (Loc)",
    "GeogName3 (Loc)",
    "GeogName4 (Loc)",
    "GeogName5 (Loc)",
    "GeogScheme1 (Loc)",
    "GeogScheme2 (Loc)",
    "GeogScheme3 (Loc)",
    "GeogScheme4 (Loc)",
    "GeogScheme5 (Loc)",
    "LocCurrency (Loc)",
    "LocExpiryDate (Loc)",
    "LocGroup (Loc)",
    "LocInceptionDate (Loc)",
    "LocName (Loc)",
    "LocNumber (Loc)",
    "LocPeril (Loc)",
    "LocPerilsCovered (Loc)",
    "LocUserDef1 (Loc)",
    "LocUserDef2 (Loc)",
    "LocUserDef3 (Loc)",
    "LocUserDef4 (Loc)",
    "LocUserDef5 (Loc)",
    "OrgConstructionCode (Loc)",
    "OrgConstructionScheme (Loc)",
    "OrgOccupancyCode (Loc)",
    "OrgOccupancyScheme (Loc)",
    "PortNumber (Loc)",
    "PostalCode (Loc)",
    "ReinsTag (Loc)",
    "StreetAddress (Loc)"
]```
Of these the mandatory (required) loc. file columns which are string columns are
```[
    "AccNumber (Loc)",
    "CountryCode (Loc)",
    "LocCurrency (Loc)",
    "LocNumber (Loc)",
    "LocPerilsCovered (Loc)",
    "PortNumber (Loc)"
]```
So you could amend the relevant code in lookup factory to explicitly set the data types for these columns in the loc. file it receives from the manager to `object` when calling `get_dataframe`.

**Comment by sr-murthy** [comment]
I would add that a good fix for this issue should not involve hard coding these column names in the code - this is an ugly solution, and increases the chances of runtime errors. The column names should be obtained by appropriately reading a JSON profile (a static JSON file placed in the package data `oasislmf/_data`, not a dict in a Python module). Column names and properties are subject to change, and using a JSON profile would mean the changes can be made offline without causing runtime errors in the code, and also allows the code to be written in a more generic way.

**Comment by hchagani-oasislmf** [comment]
Submitted a PR. At the moment, only columns of data type `string` are affected. Should the same be done for other data types?

**Comment by hchagani-oasislmf** [comment]
Tested with data that was causing the problem. Passes. Merged into `develop` in time for next release. However, `FlexiLocZZZ` column hardcoded in `get_dataframe` method in `utils/data.py`. Will need to change this in future so issue remains open.
