### ISSUE TITLE
FM tests

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#385]
ongoing task to bring across test cases from RTT into oasislmf
Completed fm24, fm27.

**Comment by johcarter** [comment]
These are still todo
ests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_different_inuring_levels SKIPPED [ 89%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_multiple_cxl_at_same_inuring_level SKIPPED [ 90%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS SKIPPED [ 91%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_QS_with_location_level_risk_limits SKIPPED [ 93%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_cxl SKIPPED [ 94%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_all_risks SKIPPED [ 95%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_PR_loc_filter SKIPPED [ 97%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_loc_level_fac SKIPPED [ 98%]
tests/acceptance/test_fm_acceptance.py::FmAcceptanceTests::test_ri_single_pol_level_fac SKIPPED [100%

**Comment by mpinkerton-oasis** [comment]
@johcarter what is the status of this?

**Comment by johcarter** [comment]
[Summary of FM tests in Oasis.xlsx](https://github.com/OasisLMF/OasisLMF/files/4343098/Summary.of.FM.tests.in.Oasis.xlsx)
