### ISSUE TITLE
Option to store the `message` field for successful lookup results

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#398]
> from Daniel Evans 

Our lookup code returns a fairly detailed status for aggregated exposures - we get a status (and separate lookup data) for each disaggregated location, but have to bundle them all up before returning to Oasis - but I can't find anywhere in the Oasis outputs that includes it.

**Comment by sambles** [comment]
Further work #411

**Comment by DanielFEvans** [comment]
Thanks for the quick turnaround on this

**Comment by sambles** [comment]
> Thanks for the quick turnaround on this (noting that you've still got to actually attach it to the CLI/Settings).

In `1.4.2` successful messages it will be added by default when running with `--lookup-complex-config-json` once that flag has been rolled into a single `--lookup-config-json` we would need to either add an option in the lookup config or add a separate cli option
