### ISSUE TITLE
Schema for model_settings and analysis_settings

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#405]
Create schemas for model_settings and analysis_settings

**Comment by ndaqjn** [comment]
From JBA

> 

> I think there are some areas of this file format that could be improved
> •	For the dropdown menu, I really think the mapping should be reversed such that the options > in the dropdown list are passed as the keys the dictionary and the objects to be passed to > > > analysis_settings.json should be the values of the dictionary. It is more intuitive this way round > and makes writing schema much simpler.
> •	Concerning the UI slider, I am unsure as to how precise this will be. I also don’t have access > to the OASIS UI, so I can’t test if it is easy to choose a value of 0.75 or be forever stuck on > > > 0.7497623… etc…
> •	The crossover of python and json objects in a .json file is confusing to me. E.g. boolean vs > > bool, object vs dictionary. If my understanding is correct and the “type” key simply relates to > > the type of widget used, could we instead populate something like “widget_type” with the type > of widget? E.g. “type”: “Boolean” -> “widget_type”: “Checkbox”.

**Comment by sambles** [comment]
First pass for model_settings
https://github.com/OasisLMF/OasisLMF/commit/7c9e503b39206d4125b2ab74bb32cb3288c43737

**Comment by mpinkerton-oasis** [comment]
@sambles can this be closed now?

**Comment by sambles** [comment]
Current schema:
https://github.com/OasisLMF/OasisLMF/blob/4119d60cc00cd1e54b879e2e45dc4fcbc3b32841/schemas/model_settings.json
