### ISSUE TITLE
Peril Handling in Input Generation

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#413]
Keys lookup logic should include some logic around perils for the model in question.

Exposure inputs form OED will have LocPerilCovered data to show which perils the location is covered for. This needs to be taken into account when returning keys form a model. Models will need to have some information about which perils are covered (in the model resources file) and keys should only be returned for perils locations which have one more locperilscovered values which match the model covered perils.

Examples:

Location1 LocPerilCovered = "WTC"; Model Perils = "WTC;WSS"
 - Keys returned for WTC and WSS
Location 2 LocPerilCovered = "WSS"; Model Perils = "WTC;WSS"
 - Keys returned for WTC and WSS
Location 3 LocPerilCovered = "OSF;OSR"; Model Perils = "WTC;WSS"
 - No Keys Returned (error message, no covered perils)

Ground Up Loss should cover all possible losses for relevant perils in the model. The FM logic will need to take into account the LocPerilsCovered and zero out any non-covered peril items in the gross loss calculations.

Examples:

Location1 LocPerilCovered = "WTC"; Model Perils = "WTC;WSS"
 - Keys returned for WTC and WSS
 - Limit of zero applied at level 1 in FM for WSS item
Location 2 LocPerilCovered = "WSS"; Model Perils = "WTC;WSS"
 - Keys returned for WTC and WSS
 - Limit of zero applied at level 1 in FM for WTC item
Location 3 LocPerilCovered = "OSF;OSR"; Model Perils = "WTC;WSS"
 - No Keys Returned (error message, no covered perils)
 - No items generated, so no action in FM

There will also need to be a mapping for combined peril codes (e.g. WW1 = all windstorm perils) so that exposure perils and model perils can be cross referenced.

**Comment by jones-matt** [comment]
I think there is an open question about the definition of ground-up loss and whether this should depend on the perils specified in the LocPerilsCovered field in the input OED loc file.

One view is that LocPerilsCovered should act to exclude those perils not included within the field and that the ground-up loss reflect this.

The other argument is that the ground-up loss should include everything (that is switched on / included in the model) - and it is only when we get into insurance coverage /conditions (i.e. gross loss) that any peril exclusions should occur. 

When I have asked cat analysts on their preference for a ground-up loss definition the feedback is normally split fairly evenly.

My own preference is to keep the ground-up loss definition broad - i.e. to include all perils that the model can generate for the given location and to only start restricting loss based on peril type when we get into gross losses.

The ORD specification should allow peril (and coverage) resolution losses to be output so if some companies do want to apply a peril specific ground-up loss definition they could still do this in future if we keep the ground-up loss definition broad from an Oasis perspective.

**Comment by jones-matt** [comment]
I have 2 suggested changes to the initial specification:
1) For the Location 3 example (LocPerilsCovered = "OSF; OSR") then I think the WTC and WSS keys should still be returned (as for locations 1 and 2) so there will be ground-up loss generated. i.e.  LocPerilsCovered should be ignored for ground-up loss.
2) For Gross loss, then PolPerilsCovered also needs to be considered as well as LocPerilsCovered.

**Comment by jones-matt** [comment]
Following various discussions with vendors the suggested behaviour for ground-up loss is to use LocPerilsCovered to define the keys returned and therefore the ground-up loss.

**Comment by benhayes21** [comment]
https://oasislmf.github.io/developer_guide/keys_lookup_service.html
