### ISSUE TITLE
Make OED LocNumber, AccNumber, PolNumber fields explictly string types on import

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#415]
AccNumber, PolNumber, LocNumber in OED location and account field, are not being imported explictly as strings in the logic that generates the fm files for the direct insurance.

In the reinsurance logic, the above fields are read in as as strings in the reinsurance scope file but but as integers in the location/account file where the ids are integers, causing a mismatch.

Mark to triage

**Comment by johcarter** [comment]
[piwind10.tar.gz](https://github.com/OasisLMF/OasisLMF/files/4016278/piwind10.tar.gz)
[piwind10_string.tar.gz](https://github.com/OasisLMF/OasisLMF/files/4016279/piwind10_string.tar.gz)
Here is an example @sambles . In piwind10_string, i have converted numerical portfolio and location  numbers to alphanumerical to force them to be strings. The reinsurance losses are correct (net < gross). 

Without making this change, and with everything else the same, you can see that the reinsurance is not applied in piwind10 because of the mismatch in data type (gross = net).

**Comment by sambles** [comment]
Found the problem: the node tree structure was not explicitly storing these as strings.
should be fixed with 6580e11b6574e8ff1ce9165e4ebb79318e358069
