### ISSUE TITLE
Add option to disable ktools error monitor 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#434]
> the latest OasisLMF is killing off our model as we send log output to stderr, and the ktools_monitor.sh script kills off the whole run if anything gets output to the stderr log. Any thoughts on tackling that? It's currently convenient that any logging we do during the loss calc phase gets placed into the run log file.

For runs using the MDK added `--ktools-disable-guard`  which disables the above feature

Inside worker images use the ENV
```
 worker:
    
    ...
      environment:
      - OASIS_KTOOLS_ERROR_GUARD=False
```

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/tree/hotfix/ktool-error-guard

**Comment by sambles** [comment]
4449c9eb2932a386951c340a59699c577cf02e67

**Comment by DanielFEvans** [comment]
All working again with with OasisLMF v1.4.4, thanks!

Also nice to now have the stderr log output from our code being printed out in real time.

**Comment by sambles** [comment]
> All working again with with OasisLMF v1.4.4, thanks!
> 
> Also nice to now have the stderr log output from our code being printed out in real time.

Most welcome!  I've just finished building that into a `model_worker:1.3.5`  the relevant ENV option is  
`OASIS_KTOOLS_ERROR_GUARD=False`
