### ISSUE TITLE
Add validation before processing exposure

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#435]
Options:
* https://github.com/frictionlessdata/goodtables-py
* https://pypi.org/project/oedtools/

**Comment by mpinkerton-oasis** [comment]
Currently looking at goodtables as an option, for our open data sets more generally.

**Comment by sr-murthy** [comment]
I could be wrong but goodtables validation, for any particular data domain, requires a table schema designed for that domain - without some schema describing which file must contain which columns, and which data go in which columns, you can't validate. So every use case of goodtables in a specific domain will require the creation of table schema(s) unique to that domain.

As an example, to use goodtables for OED validation would require you to create a table schema for every type of OED file, something which is already part of the oedtools package, and which can be easily updated with one function call even if the underlying schema changes.

**Comment by mpinkerton-oasis** [comment]
That is correct, and this would be part of a program of work to consolidate the OED format into a data schema rather than an Excel workbook. Goodtables is one option, but there are others.

**Comment by sr-murthy** [comment]
More general schema definition languages/frameworks for CSV exist, such as

https://github.com/digital-preservation/csv-schema

which I know and have studied, but as far as I'm aware there are no Python tools for this, and it would be a very time consuming task to develop a schema for the full OED spec., which consists of over 450 different columns, spanning multiple different data types, and ranges of values for the different columns.

The worksheets in the OED Excel file already represent a file schema, e.g. in the simplest instance as CSV files. When developing a Python validation tool it is easier to work with JSON, for example, which is why JSON file and data schemas are used in oedtools (auto-generated from the CSVs). 

My point is those schemas already exist in oedtools, and can easily be auto-generated from the underlying source CSV schemas, as they are done when preparing a new release.

**Comment by mpinkerton-oasis** [comment]
JSON and JSON schema is also an option. On a more general point, it would be good to adopt a more widely used approach and tool set for OED plus the other open formats we will be supporting. I don't think a workbook + custom Python code is the best approach. Goodtables, for example, also offers other tools + capabilities off the shelf, as well as an active community of users.

**Comment by sr-murthy** [comment]
Yes, they may be options but they are not currently a reality. Any validation tool covering OED (and possibly other formats) will need to correspond to the source OED schemas developed by Simplitium. For oedtools this correspondence is maintained quite efficiently and extremely quickly via auto-generation built-in to the package.

I am not sure I follow the point about custom Python code - validation of OED files using oedtools requires no Python coding at all. The CLI exposes the validation functionality as a command, which the user can run in a standard way, just as they would with a linter.

More generally, if we are talking about any validation tool, using any language, whether it is oedtools or one based on goodtables or any other library, we are talking about a tool that has to be implemented with custom code. All applications/tools are written using custom code.

So any validation tool must contain custom Python code unique to how that tool approaches the task of validation. It is the representation of the schema and the rules of validation (derived from the data schema), and their application in detecting errors, which are the key problems. oedtools solves that problem in quite a standard way using JSON schemas directly derived from (and updatable from) the OED spec. The CLI is built on the backend, and backend is fully exposed as a set of Python libraries. In addition to validation, there are schema querying and data sampling tools. The CLI is modelled on Flake8 - validation of files produces either no output if the file contains no validation errors/warnings, or a listing of these errors/warnings, with row and column numbers to indicate the exact location of the errors.

I know goodtables - I can't speak about other formats, but in relation to OED I can't see little additional utility it provides, and absolutely none that is useful in relation to OED.
