### ISSUE TITLE
Invalid coverage file generated

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#437]
If an OED loc file has many rows with the same portnumber, accnumber and locnumber, it seems that duplicate coverage ids are generated in the coverage file. These are potentially valid OED files (there can be different peril terms for a single location across lines) but break the MDK

**Comment by sambles** [comment]
Added handing so that when duplicated `loc_id`s are found, the MDK sends a warning the to user.
```
WARNING: Duplicate keys ['portnumber', 'accnumber', 'locnumber'] detected in location file
	 oasislmf doesn't currently support multiple terms for a single location
	 dropping the following row(s): [6, 7]
```
This is a placeholder fix until we decide how to handle multiple terms per location.

**Comment by sambles** [comment]
Closing this and moving it to #558
