### ISSUE TITLE
"required" columns not always required for reading loc file

### ISSUE THREAD

**Issue by ibailey-SCOR** [OasisLMF/OasisLMF#450]
When reading the `exposure_df`, the code will raise an exception if any of `loc_num, acc_num, portfolio_num,` do not exist. However, if `loc_id` already exists in the file, these columns are not required. It would be better to read the exposure_df with no required columns, then check for these columns after the subsequent `if 'loc_id' not in exposure_df:`
 
https://github.com/OasisLMF/OasisLMF/blob/18b432fc072d3b53a928fae0ae6e9d785f75c7d9/oasislmf/model_preparation/gul_inputs.py#L154

**Comment by sambles** [comment]
I think its only safe to remove these check for GUL only runs, these columns would be needed for Insured loss and reinsurance

**Comment by ibailey-SCOR** [comment]
Another similar issue I have is in the generate_summaryxref_files. In this case, the code will raise an exception if the following columns are not there...
'CountryCode', 'LocPerilsCovered', 'LocCurrency'
... but those columns are not relevant at all once the keys lookup has been generated.

We don't have those columns because we don't need to increase the input file size with columns containing the same value over all rows.

https://github.com/OasisLMF/OasisLMF/blob/29d4b8be03eced79c8ac05d0e80e18161cefb684/oasislmf/model_preparation/summaries.py#L544

Again, I'd prefer to catch the required columns at the point they're used in the code.
