### ISSUE TITLE
Request for group_id based on user selected column of loc file

### ISSUE THREAD

**Issue by ibailey-SCOR** [OasisLMF/OasisLMF#453]
Feature request: I would like the option to set group_id based on other columns in the loc file... e.g., GeoName1. 

Currently the group_id is hard-coded to allign with the 'loc_id'...
https://github.com/OasisLMF/OasisLMF/blob/20d9701211667331fe8d777c2b8e6ba4cef6d174/oasislmf/model_preparation/gul_inputs.py#L293

An option would be to set this based on an additional argument passed to `get_gul_input_items` , e.g. group_id_col='loc_id'. The same argument can be added to manager.generate_oasis_files and passed through.

**Comment by mpinkerton-oasis** [comment]
We have been meaning to do this. @hchagani-oasislmf what's the status?

**Comment by hchagani-oasislmf** [comment]
Working on feature for user to use multiple loc fields to assign `group_id`. Could be used for a single field.

`gul_inputs_df` drops certain unneeded columns from the loc file, so must ensure columns used to determine `group_id` are not dropped. Intending to implement this with a command line argument, such as:

```
$ oasislmf model generate-oasis-files -C oasislmf.json --group-id-col GeogName1
```

Could get messy if multiple columns are used:

```
$ oasislmf model generate-oasis-files -C oasislmf.json --group-id-col GeogName1 AccNumber
```

Welcome to other suggestions.

**Comment by ibailey-SCOR** [comment]
Makes sense to me. I think there could always be an option for user defined group_id in the locfile for more than e.g. 3 columns. I vaguely remember seeing that there already is an OED column name for this. What would be more tricky is to have something like group_id linking similar coverage types within the same geographic region. I can see a possible need for that, but it wouldn't be high priority.

**Comment by hchagani-oasislmf** [comment]
I took a look through the OED spec; perhaps the loc field `CorrelationGroup` could serve this purpose? This would allow for rather complicated groupings.

I've pushed a branch of the MDK which allows one to use multiple loc fields to assign `group_id` as discussed above. You can install it in your virtual environment with the following:

```
$ pip uninstall oasislmf && pip install git+{https,ssh}://git@github.com/OasisLMF/OasisLMF.git@feature/user-selected-group-id#egg=oasislmf
```

You can now give multiple fields after the `--group-id-col` or `-G` argument on the command line to assign `group_id`. For example:

```
$ oasislmf model generate-oasis-files -C oasislmf.json --group-id-col GeogName1 AccNumber
```

I've performed some testing and it looks good. If you could test it out, it would be very much appreciated. We can incorporate it in the next release if you are happy.

**Comment by hchagani-oasislmf** [comment]
Merged into `develop` and shall be incorporated in next release. Prior to this, development version can be installed with the following:

```
pip install git+{https,ssh}://git@github.com/OasisLMF/OasisLMF
```

Closing issue and deleting `feature/user-selected-group-id` branch.

**Comment by ibailey-SCOR** [comment]
Sorry for the slow response. I just got around to testing it. I can confirm this works for me. Only minor comment is that if I call generate_oasis_files() from oasislmf.manager, I must specify the columns in lowercase, which might not always be intuitive. Is this also the case for the command line option? Anyway, I'm happy there was a warning to tell me my column name didn't exist.

**Comment by hchagani-oasislmf** [comment]
No problem. Glad to hear it works, and also that the warning proved useful.

You do not need to specify the columns in lowercase on the command line. So, `--group-id-col AccNumber` is the equivalent of `--group-id-col accnumber` (and coincidentally the command line can handle `--group-id-col aCCnUmbEr` too). The conversion to lower case is done before the list of column names is passed to `oasislmf.manager`.

**Comment by ibailey-SCOR** [comment]
Thanks. In our model development we don't use the CLI, and call the python functions from jupyter notebooks. That's why my preference is for minimal inputs processing in the cli part of the code.

**Comment by hchagani-oasislmf** [comment]
I see. Merged a quick change into `develop`. Case conversion is now performed in `oasislmf.manager` rather than being passed to the manager in lower case. Does that help? Or do you call `get_il_input_items` directly?

**Comment by ibailey-SCOR** [comment]
We only interface with the methods in the manager() class, so this is great for our use case. It would also have been fine just to highlight it in the docstring for the function.

**Comment by hchagani-oasislmf** [comment]
Great!
