### ISSUE TITLE
Model settings: new option types

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#454]
For the configuration of our model via a UI (either the Oasis UI or an external one), we require support for the following new data types:

String: A single text value input by the user, to appear in the analysis settings file as `"option_name": "some_string"`
List of string: Multiple string values input by the user for a single option, to appear in the analysis settings file as `"option_name": ["string1", "string2", "string3"]`.
Dictionary: A set of (string) key-value pairs - I'd currently envision this as being input via two columns of text boxes. To appear in the analysis settings file as `{"key1": "value1", "key2": "value2", "key3": "value3"}`.

In each case, being able to specify defaults (including default key-value pairs for the dictionary) is also required.

**Comment by DanielFEvans** [comment]
As an aside, we're wanting these for ModEx currently, and Nasdaq need them in the schema before they'll support them. Support in the Oasis UI doesn't need to follow instantly.

**Comment by sambles** [comment]
so the example input file should look something like this?
```
		"string_parameters": [{
			"name": "option_name",
			"desc": "Option for X, Y or Z",
			"default": "some_string"
		}],
		"list_parameters": [{
			"name": "option_list",
			"desc": "list is for A or B",
			"default": ["str1", "str2"]
		}],
		"dictionary_parameters": [{
			"name": "dictionary_option",
			"desc": "this Stores .. for ... etc",
			"default": {
				"k1": "v1",
				"k2": "v2"
			}
		}]
```

**Comment by DanielFEvans** [comment]
Yep, that looks like what we're after.

**Comment by sambles** [comment]
#470
