### ISSUE TITLE
Keys lookup response clean up

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#458]
Currently the default keys lookup has three return statuses: "Match", "No-match" and "Fail". For the default lookup the following logic applies:
- "Match" implies a successful area-peril and vulnerability lookup. Item will be modeled.
- "No-match" implies an unsuccessful vuln lookup. Item will not be modeled.
- "Fail" implies and unsuccessful area-peril lookup. Item will not be modelled.

This should be consolidated into the following logic in the default template, and some clear guidance provided to model developers.
"Valid - at risk" - will be modeled
"Valid - not at risk" - is in the scope of the model, but not at risk
"Invalid" - is not in the scope of the model, either outside the geography or without a vulnerability curve

**Comment by johcarter** [comment]
Regarding the logic to generate oasis input files from keys return, only valid areaperil and vulnerability ids should go into the items file. There should be no items created for coverages with 'no-match' status with special meaning ids like areaperil=-1, for example.

Regarding analysis of exposure value: the existing return status should be sufficient to be able to run exposure reports in the front end. Useful totals (from FM steering group feedback) are;
1) Programme (every coverage loaded into Oasis regardless of key server status)
2) Model domain (Subset of coverages where key service return status = Match)
The difference between Programme and Model domain to be broken down by No-match and fail.

More on exposure value definition
https://github.com/OasisLMF/OasisPlatform/issues/217

**Comment by jones-matt** [comment]
For clarity, in terms of the default keys lookup (and also the exposure summary report) is the following what happens at the moment:

1) unsuccessful vuln, successful area-peril = No-match
2) successful vuln, unsuccessful area-peril = Fail
3) unsuccessful vuln, unsuccessful area-peril = Fail

If so, I suggest adding an extra category and renaming for completeness and clarity, e.g.

1) = bad vuln
2) = bad area-peril
3) = bad vuln & area-peril

'No-match' and 'Fail' labels don't help the user understand what is really happening.

**Comment by jones-matt** [comment]
To capture all requirements it looks like we need the following response categories:

a)	Items where area/peril and vuln keys are valid
b)	Items where area/peril matches and vuln doesn’t
c)	Items where area/peril doesn’t match and vuln does
d)	Items where both area/peril and vuln do not match
e)	Catch-all not used by most models but reserved for use typically by model developers who want to explicitly flag that an item is recognised as being within the over-arching domain, but will not be considered by the model (e.g. JBA's areaperil = -1)

Only items from a) will go into the items file.

**Comment by benhayes21** [comment]
Proposed Behaviour

    1. oasislmf passes OED Location File to Keys Server
    2. Keys Server to use LocPerilCovered to decide on response
    3. Keys Server returns response by:
        a) loc_id
        b) peril
        c) coveragetypeid
    4. Keys Server statuses to be updated to:
        a) success
        b) fail
        c) fail_v
        d) fail_ap
        e) not_at_risk
    5. oasislmf does not interpret or validate returned peril codes (i.e. accepts anything)
    6. oasislmf interprets legacy statuses as:
        a) success → success
        b) fail → fail
        c) nomatch → fail
    7. oasislmf maps only success responses to ktools files
    8. oasislmf generates exposure summary report at lowest level (loc/peril/coverage)
    9. number_of_locations and tiv values will be distinct but not additive
        a) a location can be a success for one sub-peril and not for another
        b) a location can be a success for one coverage type and not for another
    10. exposure summary file will adjusted to be grouped by returned peril code, and not by description as no interpretation of peril codes will happen in oasislmf
    11. exposure summary file will group in the following way:
        a) modelled tiv = Σ location level tiv (success + not at risk)
        b) not modelled tiv = Σ location level tiv (fail + fail_v + fail_ap)
        c) portfolio tiv = Σ location level tiv (all)
        d) modelled locations = Σ count distinct loc_id (success + not at risk)
        e) not modelled locations = Σ count distinct loc_id (fail + fail_v + fail_ap)
        f) portfolio locations = Σ count distinct loc_id (all)
    12. number_of_locations will be distinct loc_id and calculated independently at each level (i.e. not additive)


We should also write a best practice document for the keys server and distribute to all existing working model providers. However, the code should be backwards compatible in such a way as to not break any existing keys server interactions.

**Comment by jones-matt** [comment]
Just to clarify: 

1) 'fail' means vulnerability and area-peril have both failed?
2) within each of 11a) - 11f) there is no double counting of TIV or location numbers? So for example  if there are 2 sub-perils modelled for the same location I will not double the modelled tiv in 11a?

If so this looks good to me @benhayes21

**Comment by benhayes21** [comment]
@jones-matt yes, that's correct. A couple of points to clarify:

1) Fail will be defined as both ap and v failing, though this is up to the model providers to implement. This will not have any effect on the actual execution but should be applied and encouraged as best practice for models in Oasis.
2) There will be no double counting within a metric as you suggest - but there is the distinct possibility that a single location can both be modelled and not-modelled, so the results will not be additive. For example, a single location could be modelled for wind and not modelled for surge within the same model, so we would see 1 location in the modelled location count, 1 location in the not-modelled locations and 1 location in the total.
