### ISSUE TITLE
fm file generation error - duplicate from_agg_id keys in programme file

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#459]
Duplicate from_agg_id keys are being generated in the fm_programme file in the final level (the level at which policy layers are applied) when there are **multiple layers** (layer_id >1) in the policytc file.  A contributing factor may be the existence of the same LocNumber for different AccNumbers.

Test case 1 (tc1) is a single layer example where the fm_programme is correct (no duplicates in from_agg_id at level 4)
Test case 2 (tc2) is the same as tc1 except has a second layer added for one account, and the fm_programme has duplicates in from_agg_id at level 4.

More info and potential solution:
Iain Bailey 4:57 PM
Hi @Joh Carter and @Sam Gamble - I've done some more debugging on this and found two more issues. Firstly the duplicate locnumbers are probably a problem, since the agg_id's are assigned using factorization based on locnumber, so I should correct the input file. Secondly, there is an issue with the code. The il_inputs are not necessarily in the same order for the topmost level when layers are present, but this is assumed by the code. This causes a mismatch in the from_ and to_ agg_ids when constructing the fm_programme_df. It is fixed by sorting the il_inputs_df after adding the layers in. e.g on [line 532]....
il_inputs_df = il_inputs_df.sort_values(['level_id', 'layer_id', 'loc_id',
                                         'coverage_id']).reset_index(drop=True)

**Comment by sambles** [comment]
Fix merged in, but still an issue with column length mismatch when building the last level of the fm_programme file (in some cases)
```
ValueError: array length 100401 does not match index length 140388
```

**Comment by sambles** [comment]
should be fixed with:
https://github.com/OasisLMF/OasisLMF/commit/1a969950612b9cd6eebd92f852fd6ee392ed5212
https://github.com/OasisLMF/OasisLMF/commit/94d0c46b6ac847ee10419db8c51b70e072e58830
