### ISSUE TITLE
Exposures with deductible and no limit are matched to incorrect T&Cs

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#463]
The following abbreviated input portfolio Loc file contains Limits and Deductibles defined at location level. The deductibles are identical between the exposures, but the limits vary, with some exposures having no limit:

```
LocNumber,LocDed6All,LocLimit6All
1,250.00,
2,250.00,5000.00
3,250.00,7000.00
4,250.00,9000.00
5,250.00,
6,250.00,9000.00
7,250.00,5000.00
8,250.00,
```

Running via Oasis, the generated `fm_profile` file contains all of the T&C combinations that should be present:

```
policytc_id,calcrule_id,deductible1,limit1
1,12,0.0,0.0
2,12,250.0,0.0
3,1,250.0,5000.0
4,1,250.0,7000.0
5,1,250.0,9000.0
6,2,0.0,9999999999.0
```

However, following through the association of T&Cs in the various Oasis files, the locations with no limit are (sometimes) linked another of the T&Cs containing a limit. Note that LocNumber 5 and 8, which have a limit of 0 in the portfolio, are associated with non-zero limits:

```
LocNumber,agg_id_level_2,policytc_id_expected,policytc_id_actual,limit_expected,limit_actual
1,1,2,2,0.0,0.0
2,2,3,3,5000.0,5000.0
3,3,4,4,7000.0,7000.0
4,4,5,5,9000.0,9000.0
5,5,5,2,0.0,9000.0
6,6,5,5,9000.0,9000.0
7,7,3,3,5000.0,5000.0
8,8,3,2,0.0,5000.0
```

This has been observed to occur in OasisLMF v1.4.0 and v1.4.5.

Example portfolio and generated inputs will be sent separately.

**Comment by johcarter** [comment]
replicated in 1.4.6 using oasislmf exposure run (the problem is independent of key service)
Locations ( and agg_id) 5 and 8 are being assigned the wrong policytc_id (5 and 3, should be 2). Note that explicitly setting null limits to zero solves the problem

**Comment by johcarter** [comment]
[oed_input.zip](https://github.com/OasisLMF/OasisLMF/files/4030246/oed_input.zip)

**Comment by sambles** [comment]
[463-post-fix.zip](https://github.com/OasisLMF/OasisLMF/files/4046188/463-post-fix.zip)
