### ISSUE TITLE
Refresh Sphinx docs in OasisLmf

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#465]
Refresh Sphinx docs in OasisLmf

**Comment by mpinkerton-oasis** [comment]
Experimenting with sphinx-autoapi to remove the need for manually creating all of the rst files.

**Comment by diversemix** [comment]
Consider putting the building of the documents in tox - see for example  [flask-sqlalchemy](https://github.com/pallets/flask-sqlalchemy/blob/db02fd4c821b8aa8c6e47391fce6f064def6a363/tox.ini#L22)

**Comment by mpinkerton-oasis** [comment]
Docs have been updated and integrated with release process.
