### ISSUE TITLE
No exposure summary produced for Corelogic US EQ model

### ISSUE THREAD

**Issue by lucaspanayiotou** [OasisLMF/OasisLMF#466]
corelogic worker image tag: 1.4.1-rc1

We are still not seeing exposure summaries. We have enabled WRITE_EXPOSURE_SUMMARY=True in the YML file.

Here are the comments from Sam.

> I suspect the summary reporting module is failing because it can't interpret the keys return from CoreLogic so it continues the files generation without creating the report

**Comment by lucaspanayiotou** [comment]
[corelogic 1.4.1-rc1 Logs.zip](https://github.com/OasisLMF/OasisLMF/files/4035115/corelogic.1.4.1-rc1.Logs.zip)

**Comment by sambles** [comment]
The Report isn't generated because the Peril returned is not in OED code format

**From the logs:**
```
summaries.py:780: UserWarning: "63" is not a valid OED peril ID/code. Please check the source exposure file.
```

What should the correct behaviour be?  we could say change this line:
https://github.com/OasisLMF/OasisLMF/blob/35c61b685312dbb04d2d3f4c1319618e940883e3/oasislmf/model_preparation/summaries.py#L794

To `peril_key = peril_id`  which would create the report with whatever the keys lookup. However it seems to return 0.0 TIV's 
```
{                                                                                                                                                                                                                                                                            
    "63": {
        "all": {
            "tiv": 0.0,
            "tiv_by_coverage": {
                "buildings": 0.0,
                "other": 0.0,
                "contents": 0.0,
                "bi": 0.0 
            },  
            "number_of_locations": 0
        },  
        "success": {
            "tiv": 0.0,
            "tiv_by_coverage": {
                "buildings": 0.0,
                "other": 0.0,
                "contents": 0.0,
                "bi": 0.0 
            },  
            "number_of_locations": 0
        },  
        "fail": {
            "tiv": 0.0,
            "tiv_by_coverage": {
                "buildings": 0.0,
                "other": 0.0,
                "contents": 0.0,
                "bi": 0.0 
            },  
            "number_of_locations": 0
        },  
        "nomatch": {
            "tiv": 0.0,
            "tiv_by_coverage": {
                "buildings": 0.0,
                "other": 0.0,
                "contents": 0.0,
                "bi": 0.0 
            },  
            "number_of_locations": 0
        }   
    }   
}
```

**Comment by mpinkerton-oasis** [comment]
Closing - CL team need to fix on their side to return correct peril codes.
