### ISSUE TITLE
Tox fails locally

### ISSUE THREAD

**Issue by diversemix** [OasisLMF/OasisLMF#472]
### Main Issue
Running `tox` locally results in `FileNotFoundError: [Errno 2] No such file or directory: 'oasislmf': 'oasislmf'` as the acceptance tests rely on `oasislmf` being installed locally. 

### Suggested Enchancement
Arguably the acceptance tests could be run at a later stage in the pipleline - thus allowing the unit tests to run quicker. This would mean more rapid development. My suggestion would be to only run the acceptance tests on merging to master - in this way the mainline code remains fully tested but allows developers a more rapid development cycle. I'd say this would be dependent on increasing unit test coverage first (currently at 49%)

When tox can be run locally you may consider migrating to [github actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-python-with-github-actions#running-tests-with-tox) which would allow including the [acceptance tests on merging to particular branches](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths)

**Comment by mtazzari** [comment]
Thank you for reporting this issue and for your suggestion.

We now have a GitHub Actions workflow for unit tests (link [here](https://github.com/OasisLMF/OasisLMF/blob/master/.github/workflows/unittest.yml)) that is executed on each push to the repository, on any branch.
Running these tests well before the code gets integrated on master is helpful to spot issues early.

As you can see from the GitHub Actions workflow, to run tox locally, the `oasislmf` package needs to be installed together with other requirements. This works locally as of for `oasislmf` v1.27.0rc3, but probably also with previous oasislmf versions:
```bash
git clone https://github.com/OasisLMF/OasisLMF.git
cd OasisLMF/
pip install -e .
pip install --upgrade pip
pip install pip-tools
pip-compile requirements.in -o requirements.txt
pip install -r requirements.txt
tox -e py
```
