### ISSUE TITLE
OasisLMF may copy the entire model data directory to networked output

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#475]
We set up an OasisLMF run on a Linux machine, with the run outputs pointed to a networked (non-Linux-based) drive, which is one of our centralised data storage devices, and also provides much more space than is available on a local machine (OasisLMF outputs and intermediate data can be large, especially if doing a few dozen runs).

However, we've found that OasisLMF is copying the entire model data directory across to the run outputs directory - i.e. somewhere around 1TB of data over the network.

This has occurred following the `STARTED: oasislmf.model_execution.bin.prepare_run_directory
` log entry. I believe it's in the linking of the `static` data directory within the run directory. This is usually symlinked to the model data directory, which is failing (and falling back on copying) when referencing local data from a networked (non-Linux-based) drive.

OasisLMF v1.4.5 for reference, although I don't think this particular functionality has changed in a while.

**Comment by sambles** [comment]
It might be from here?  It should only trigger if the host system is windows
https://github.com/OasisLMF/OasisLMF/blob/29d4b8be03eced79c8ac05d0e80e18161cefb684/oasislmf/model_execution/bin.py#L152-L153

from [PR 216](https://github.com/OasisLMF/OasisLMF/pull/216)

**Comment by sambles** [comment]
oh wait, i see what you mean:
https://github.com/OasisLMF/OasisLMF/blob/29d4b8be03eced79c8ac05d0e80e18161cefb684/oasislmf/model_execution/bin.py#L157

Any idea what the Exception is?

**Comment by DanielFEvans** [comment]
Good spot. I'm getting:

```
>>> os.symlink(os.path.join(in_path, filename), os.path.join(out_path, filename))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 95] Operation not supported: '/home/jbanorthwest.co.uk/danielevans/foo' -> '/media/LiveData/2018/Projects/2018s0569 - JBA Risk Management Ltd - Global Flood Model Development/Software Development/foo'
```

On playing around in the terminal, I get the somewhat more explanatory:

```
(farmcat3) [danielevans@rml-dev06 Software Development]$ link ~/foo foo
link: cannot create link ‘foo’ to ‘/home/jbanorthwest.co.uk/danielevans/foo’: Invalid cross-device link
```

Which makes sense - the network drive can't hold a reference back to an unshared local drive.
