### ISSUE TITLE
symlink error when rerunning analysis using existing analysis_folder

### ISSUE THREAD

**Issue by ibailey-SCOR** [OasisLMF/OasisLMF#482]
os.symlink will raise an exception if the destination already exists. So the following will cause generate_model_losses to crash if you try to reuse an existing analysis folder...

https://github.com/OasisLMF/OasisLMF/blob/29d4b8be03eced79c8ac05d0e80e18161cefb684/oasislmf/model_execution/bin.py#L155

What do you think about adding the following except?
```
    try:
        # Use symbolic link if we can
        os.symlink(sourcefile, destfile)

    except OSError as why:
        if why.errno == errno.EEXIST and os.path.islink(destfile):
            # If the link already exists, check files are different replace it
            if os.readlink(destfile) != os.path.abspath(sourcefile):
                os.symlink(sourcefile, destfile + ".tmp")
                os.replace(destfile + ".tmp", destfile)


```

**Comment by sambles** [comment]
Added it in, thanks for the suggestion!
