### ISSUE TITLE
oasislmf exposure run support for loss ratio = 0

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#491]
when entering a loss ratio of 0 via CL switch

$ oasislmf exposure run -l 0 ...

 the loss ratio used is 1 and should be 0.

**Comment by johcarter** [comment]
please could you take a look at this one @hchagani-oasislmf ? low priority

**Comment by hchagani-oasislmf** [comment]
The default value of `loss_factor = 1.0` when reading `-l 0` from the command line. This is because of a quirk in the logic in `InputValues.get`. Solved by explicitly stating `type=float` when calling `get`. Built a few tests too for float input values.
