### ISSUE TITLE
Outstanding step policy features

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#498]
- Test case D5 requires more information.
- Test case B13 is not a step policy but it needs to implemented and tested as a normal policy
- Work is needed to ensure standard policy terms are calculated normally when combined with step policies. this involves aligning the aggregation tree for step and non-step.

**Comment by johcarter** [comment]
[oed_step_policies_v5.xlsx](https://github.com/OasisLMF/OasisLMF/files/4166326/oed_step_policies_v5.xlsx)

**Comment by johcarter** [comment]
[oed_step_policies_status.xlsx](https://github.com/OasisLMF/OasisLMF/files/4166329/oed_step_policies_status.xlsx)

**Comment by benhayes21** [comment]
Closing issue but will re-open if any additional functionality is required by used

**Comment by johcarter** [comment]
Add a rule which is the same as 28 plus a limit on payout

**Comment by johcarter** [comment]
* consider handling of OtherTIV and BITIV

**Comment by johcarter** [comment]
This is a test case for combining step with non-step policy terms (based on fm54) which produces the wrong results for both policies.
B1 is a simple step policy, B2 is a standard policy with coverage, combined, site, and policy deductible plus layer terms.
[fm54_terms.zip](https://github.com/OasisLMF/OasisLMF/files/6500068/fm54_terms.zip).
What happens is that the aggregation hierarchy logic for the step pol is ignored when the standard terms are introduced. the fm_programme file aggregates all items by coverage (level1), then combined (level2), then site (level3), then pol (level 4 and 5). What needs to happen is to apply the separate grouping logic to each policy and then stitch it together.  In this example, the step policy has 2 levels and the standard policy has 5 levels. the step policy hierarchy has to extend to 5 levels using passthrough rules for the extra 3 levels.
fyi @sstruzik

**Comment by johcarter** [comment]
replaced by #829 and #830
