### ISSUE TITLE
fix fm12 acceptance test

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#508]
fm12 - 1 special condition with 3 aggs and 7 policy layers - is broken because the multiple records in the account file for each special condition agg group are being interpreted as layers. therefore we are getting 21 layers (7*3) rather than 7 layers.

please can you take a look @hchagani-oasislmf ? high priority

thanks
joh

**Comment by hchagani-oasislmf** [comment]
Fixed the above issue in branch `fix/fm12-acceptance-test` so now 7 layers are given. Passes all current acceptance tests. However, fails `fm12` test when added to branch. Are expected files correct and this requires further investigation?
