### ISSUE TITLE
OasisLMF error in run_analysis that settings is not in the object.

### ISSUE THREAD

**Issue by jmosscl** [OasisLMF/OasisLMF#511]
I am getting an error with the OasisLMF api 1.5.1 version. When running the script, it is choking at run_analysis. I was able to get a potential fix by modifying the line
self.upload_settings(analyses, analysis_settings_fp) to
self.upload_settings(json.loads(analyses.text), analysis_settings_fp)
inside the run_analysis method.  Someone with more understanding of this method should put in whatever appropriate fix is needed.

**Comment by sambles** [comment]
Thanks for the issue, updated the method to use `analyses_id` which an `int` id to select an analyses rather than the JSON analyses response.
