### ISSUE TITLE
generated loc_id is dropped

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#515]
loc_id is generated from the input location OED file and passes to the keys service to be used as the identifier for the returned keys, but it is only written out to the gul summary map for successful records. 

This means that the loc_id is not persisted anywhere for rejected keys records except for the keys error file, so it is impossible to know which locations have actually been rejected.

A persisted file is required to understand the mapping of gnereated loc_id to PortNumber, AccountNumber and LocationNumber

**Comment by sambles** [comment]
PR #520
