### ISSUE TITLE
"/bin/sh: BASH_XTRACEFD: 19: invalid value for trace file descriptor" during loss calculations

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#519]
When running OasisLMF, we've quite often seen this line printed out one or more times:

`/bin/sh: BASH_XTRACEFD: 19: invalid value for trace file descriptor`

It doesn't seem to cause any problem, but it does occasionally cause some concern to users who have seen it appearing in logs.

This is presumably coming from run_ktools.sh, the ktools monitor script, or something related to them.

From the SO post below, it sounds like stream 19 should be being set up to pipe to a log file (or other program), but it isn't: https://stackoverflow.com/questions/56872211/bash-bash-xtracefd-5-invalid-value-for-trace-file-descriptor

**Comment by sambles** [comment]
so what its doing it redirecting the the bash trace `set -x` to another stream from `stderr` (the default) 

It prevents the ktools error guard being tripped when output is detected on `stderr` from ktools components while logging the script trace from  `run_ktools.sh` when the flag `--verbose` is set on command line or `DEBUG_MODE==True` in a worker. 

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_execution/bash.py#L812-L818

It should setup the file descriptor `log/bash.log` before invoking `BASH_XTRACEFD`

**Comment by sambles** [comment]
interestingly it should be running under `/bin/bash` not `/bin/sh` which might be why your seeing an error

**Comment by DanielFEvans** [comment]
It does look like the commands should set it up properly - this is appearing in `run_ktools.sh`:

```
exec 19> log/bash.log
export BASH_XTRACEFD="19"
```

And there's no obvious reason for it to be running via `sh` - the OasisLMF code and script both specify `bash`. I wonder if the mention of `sh` in the error is unimportant and just trying to mislead us?

(In short, I don't understand what's going on, either)

**Comment by sambles** [comment]
which image is your worker based on? could the default shell be `sh` rather than `bash`?

**Comment by DanielFEvans** [comment]
This is running from the command line on a Linux box, rather than in a docker container, and `bash` is the default shell.

**Comment by sambles** [comment]
Note: happens on CLI on the 'Scientific Linux' distribution

**Comment by sambles** [comment]
Didn't manage to reproduce on Scientific Linux 7 via docker, closing this for now as it doesn't seem to be a blocking issue
