### ISSUE TITLE
MDK run directory name

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#522]
when running the MDK, the default generated run directory name is `ProgOasis-xxxxxxxxx` which is a relic of the old flamingo system. Suggest this is renamed to something appropriate

**Comment by sambles** [comment]
switched `oasislmf model generate-oasis-files ..` to:
```
<pwd>/runs/files-xxxxxxxxx
```

and `oasislmf model generate-losses ..` to 
```
<pwd>/runs/losses-xxxxxxxxx
```

**Comment by benhayes21** [comment]
Sounds good. Would be good to have generate-keys following a similar pattern. At the moment, I think the keys files are just dumped in the root.

**Comment by sambles** [comment]
good spot, i've moved ` oasislmf model generate-keys ...` to
```
<pwd>/runs/keys-xxxxxxxxx
```
