### ISSUE TITLE
item file ordering of item_id

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#531]
the item file generation does not have any explicit ordering on the data-frame prior to assignment of the oasis ids (item_id, coverage_id, group_id). With the old implementation (in SQL Server) the ordering of the intermediate tables could not be guaranteed as SQL Server will reorder things to manage space. It's unclear if Pandas does the same thing but explicit ordering of the intermediate data-frame prior to assignment of the ids would be safer and more transparent.

 Ordering on source fields (portfolio, account, location number) along with coverage type and OED peril code would also give us consistency if the source file is re-ordered for any reason. 

This is important because the combinations of the oasis ids drive the random number seed in the loss simulations, so different a conceptual exposure item with a different id will get a different loss.

**Comment by DanielFEvans** [comment]
> It's unclear if Pandas does the same thing

I'd expect the ordering to remain constant for the same series of operations - I think the comment about the SQL server implementation is saying that the order would change for repeat runs?

It does still make sense to sort, though, as it gives you the freedom to change parts of the code later without worrying about preserving order, and makes you resilient against changes in the Pandas library.

Is it worth considering whether the Oasis IDs should be resilient to the insertion of new records? If I add a new row PortNumber,AccNumber,LocNumber 0,0,0, and we assume it's sorted to the top, is it acceptable that the results for every other row change as a result of all Oasis IDs being offset by one compared to the original portfolio?

Similarly, if the stage that includes assignment of Oasis IDs moves (if it hasn't already) to a parallelised implementation, or one where exposures are processed sequentially in smaller chunks to limit memory use, you'll need to ensure that the various versions give the same IDs, which makes life a bit more difficult.
