### ISSUE TITLE
GUL Alloc Rule 0 doesn't work in oasislmf package

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#548]
line 672 in model_execution/bash.py uses:

`gul_item_stream = (gul_alloc_rule and isinstance(gul_alloc_rule, int))`

which interprets gul_alloc_rule as False when gul_alloc_rule = 0, so the gul_item_stream is not used.

line 273 has a similar condition:

`if gul_alloc_rule:`

which is also interpreted as False for gul_alloc_rule = 0

**Comment by sambles** [comment]
Issue Notes: 
Originally `-a0` was used to selected the now deprecated  (item/coverage) stream type.  

Now that  `--ktools-alloc-rule-gul 0`  is an valid allocation rule:
*  The option needs to be changed to add `gulcalc -a0 -i - ` using the new stream type
* A separate option added to change to the old stream types (only if needed)

**Comment by sambles** [comment]
Note: 
* default == 0
* option should be defined in model_settings

**Comment by sambles** [comment]
Added a new flag **--ktools-legacy-gul-stream** to revert to deprecated item/coverage, this overrides any options set for **--ktools-alloc-rule-gul**
