### ISSUE TITLE
Unexpected calculation rule mapping error

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#553]
Using oasislmf exposure run, i'm getting an unexpected calculation rule mapping error on the attached set of oed files. Please could one of you help debug?

Calculation Rule mapping error, non-matching keys:
   ('deductible_gt_0', 'deductible_min_gt_0', 'deductible_max_gt_0', 'limit_gt_0', 'share_gt_0', 'attachment_gt_0', 'ded_type', 'ded_code', 'lim_type', 'lim_code')
   (0, 1, 1, 1, 1, 0, 0, 0, 0, 0)

This key means we have a min ded, max ded, limit and share, which is an unsupported combo.  

What we actually have in the location file is a ded%loss, min ded, max ded for buildings , i.e.
(1, 1, 1, 0, 0, 0,1, 0, 0, 0) - supported
and limit only for contents. i.e.
(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)

[debug.zip](https://github.com/OasisLMF/OasisLMF/files/4546073/debug.zip)

**Comment by hchagani-oasislmf** [comment]
I see the issue: it lies with `il_inputs_df.loc[3:]`. As `il_inputs_df` is being created, default values are written. The issue crops up in `utils.defaults.assign_defaults_to_il_inputs`. For the `policy layer` level, the defaults for `limit` are set with the following logic:

```'limit': {'condition': '!= 0', 'default_value': 9999999999}```

Or in other words, if `limit == 0` then the default value is set to 1e10.

Again, for the `policy layer`, the defaults of `deductible` are set with the following logic:

```'deductible': {'default_value': 0}```

Or in other words, `deductible = 0` regardless of its initial value.

Finally, for the `policy layer`, the defaults of `ded_type` are set with the following logic:

```'ded_type': {'default_value': 0}```

Or in other words, `ded_type = 0` regardless of its initial value.

Therefore, before this method, the entry in question has `deductible = 0.1`, `limit = 0` and `ded_type = 1`. This would translate to `id_key = (1, 1, 1, 0, 0, 0, 1, 0, 0, 0)`. After this method, the entry in question has `deductible = 0`, `limit = 1e10` and `ded_type = 1`, which translates to `id_key = (0, 1, 1, 1, 0, 0, 0, 0, 0)`.

@johcarter Can we change the default values? Or remove the assigning of default values for the aforementioned terms? Or perhaps change the logic/condition?

**Comment by johcarter** [comment]
Thanks for looking, @hchagani-oasislmf . i remember when we decided to put the default values into  _data/default_fm_profile_field_values.json. 

what confuses me is that the level of the terms we have here are "site coverage"  so why does the policy level default logic apply? policy terms are empty so that should invoke a separate key with the default values of 999999999 for the limit and 1 for the share. 

Is the key being conflated across levels?

**Comment by hchagani-oasislmf** [comment]
Before defaults are assigned to `il_inputs_df`, it looks like this:

```
(Pdb) il_inputs_df[['level_id', 'deductible', 'deductible_min', 'deductible_max', 'limit', 'share', 'attachment', 'ded_type', 'ded_code', 'lim_type', 'lim_code']]
   level_id  deductible  deductible_min  deductible_max  limit  share  attachment  ded_type  ded_code  lim_type  lim_code
0         1         0.1            10.0            60.0    0.0    0.0         0.0         1         0         0         0
1         1         0.0             0.0             0.0  200.0    0.0         0.0         0         0         0         0
2         1         0.0             0.0             0.0    0.0    0.0         0.0         0         0         0         0
3        10         0.1            10.0            60.0    0.0    0.0         0.0         1         0         0         0
4        10         0.0             0.0             0.0    0.0    0.0         0.0         0         0         0         0
5        10         0.0             0.0             0.0    0.0    0.0         0.0         0         0         0         0
```

Line 3 should look like this:
```
   level_id  deductible  deductible_min  deductible_max  limit  share  attachment  ded_type  ded_code  lim_type  lim_code
3        10         0.0             0.0             0.0    0.0    0.0         0.0         0         0         0         0
```
