### ISSUE TITLE
Type 2 financial terms calculation depends on coverages supported by model

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#604]
If all coverages are not supported by the model then when calculating a %TIV deductible or limit, the coverage TIV entered in the unsupported coverage(s) fields is not included in the TIV basis for calculating the deductible or limit.

E.g. BuildingTIV = 100, OtherTIV=200, CoverageTIV = 300, BITIV = 400
Model 1 covers Buildings and Contents only
Model 2 covers Buildings , Contents and BI
Site deductible = 1%

For model 1 the site deductible would be calculated as 1%*(100+300) = 4
For model 2 the site deductible would be calculated as 1%*(100+300+400) = 8

I presume the calculated deductible should be based on all coverages and not vary depending on the model, and the correct deductible is actually 10 =1%*(100+200+300+400)?

This issue affects % TIV terms at all fm levels except Cov1-4, where model does not explicitly support all 4 coverages.

**Comment by jones-matt** [comment]
yes, I agree Joh - the Type 2 calculated deductibles / limits for the '5PD' and '6All' terms should be based on the % TIV in the relevant coverage fields and should not vary according to whether a coverage is supported or not by a particular model.

**Comment by johcarter** [comment]
Thanks @jones-matt 
@hchagani-oasislmf  please could I add this issue to your list?
