### ISSUE TITLE
Integration of GUL-FM load balancer

### ISSUE THREAD

**Issue by sstruzik** [OasisLMF/OasisLMF#608]
# Specifications - Integration of Manual Load Balancer

The purpose of this document is to list what needs to be done to integrate the Python load balancer (see [load_balancer.py](load_balancer.py)).

1. Add `IL_TO_GUL_RATIO` option to `conf.ini`:

    - Description: The number of IL enginges compare to gul engines.
    - Type: integer.
    - Default value: `0` => default pipeline with no load balancer.
    - Value: `M` => 1 GUL engine will fan out to `M` IL engines.

1. Add `N_GUL` option to `conf.ini`:

    - Description: The number of GUL engines to start.
    - Type: Integer.
    - Default value: `-1` (**note:** final meaning of `-1` should be discussed)
        1. => as much GUL as the number of processes triggered by `KTOOLS_NUM_PROCESSES` value (**pros:** simple; **cons:** will oversubscribe CPU usage a lot); or
        1. => `(K * M) / (M + 1)` rounded to the closest integer (where `K` is the number of process induced by `KTOOLS_NUM_PROCESSES`). (**pros:** limit oversubscribing to the actual situtation when `KTOOLS_NUM_PROCESSES` is set to `-1`; **cons:** add complexity).
    - Value: `N` => `N` GUL will fanout to `N * M` IL with `N` load balancers. `KTOOLS_NUM_PROCESSES` is then not used.

1. Update `run_ktools.sh` script generation to include `load_balancer.py` calls.

    - if `IL_TO_GUL_RATIO` is 0, then generate the standard pipelines (no `load_bal;ancer.py` calls). The number of pipelines is based on `KTOOLS_NUM_PROCESSES` value. `N_GUL` is then not used.
    - if `IL_TO_GUL_RATIO` is not 0 then include `load_balancer.py` calls in `run_kttols.sh`:

        1. Create GUL engines (`EarthquakeDamage`) calls to output to a special FIFO that will be its load balancer input. The number of GUL engines is based on `N_GUL` option.
        1. Add one `load_balancer.py` call per GUL engine, with one input and `M` ouputs.
        1. Launch `N * M` IL processes (`fmcalc`).

Elements to add to `run_ktools.sh` (based on `M = 2`, and `N = 3`):

- Create load balancer input FIFO:

```sh
mkfifo fifo/gul2lb_P1
mkfifo fifo/gul2lb_P2
mkfifo fifo/gul2lb_P3
```

- Create load balancer output FIFO.

```sh
mkfifo fifo/lb2fm_P1
mkfifo fifo/lb2fm_P2
mkfifo fifo/lb2fm_P3
mkfifo fifo/lb2fm_P4
mkfifo fifo/lb2fm_P5
mkfifo fifo/lb2fm_P6
```

- Start load balancers processes.

```sh
# 3 load balancers (1 per GUL)
python ./load_balancer.py -i fifo/gul2lb_P1 -o fifo/lb2fm_P1 fifo/lb2fm_P3 &
python ./load_balancer.py -i fifo/gul2lb_P2 -o fifo/lb2fm_P2 fifo/lb2fm_P4 &
python ./load_balancer.py -i fifo/gul2lb_P3 -o fifo/lb2fm_P5 fifo/lb2fm_P6 &
```

- Start GUL processes.

```sh
EarthquakeDamage -m 1 -n 3 -a analysis_settings.json -p . -S20 -i - | tee fifo/gul_P1 fifo/gul2lb_P1 > /dev/null  &
EarthquakeDamage -m 2 -n 3 -a analysis_settings.json -p . -S20 -i - | tee fifo/gul_P2 fifo/gul2lb_P2 > /dev/null  &
EarthquakeDamage -m 3 -n 3 -a analysis_settings.json -p . -S20 -i - | tee fifo/gul_P3 fifo/gul2lb_P3 > /dev/null  &
```

- Start IL processes.

```sh
fmcalc -a2 < fifo/lb2fm_P1 > fifo/il_P1 &
fmcalc -a2 < fifo/lb2fm_P2 > fifo/il_P2 &
fmcalc -a2 < fifo/lb2fm_P3 > fifo/il_P3 &
fmcalc -a2 < fifo/lb2fm_P4 > fifo/il_P4 &
fmcalc -a2 < fifo/lb2fm_P4 > fifo/il_P5 &
fmcalc -a2 < fifo/lb2fm_P4 > fifo/il_P6 &
```

**Example file:** See [run_ktools_LB_2GUL_4IL.sh](run_ktools_LB_2GUL_4IL.sh) for a complete example script.

**Note:** It has not been tested with error guard.

**Comment by sstruzik** [comment]
detail on the final implementation:
the option of load balancer is activated when both --ktools-num-gul-per-lb and --ktools-num-fm-per-lb are non null.
they are set to 0 by default (meaning no load balancer)
--ktools-num-gul-per-lb represent the number of gul per load balancer
--ktools-num-fm-per-lb  represent the number of fm per load balancer

to be consistent with the other fifo name 
gul to lb are called gul_lb_P1, gul_lb_P2...
lb to fm are called lb_il_P1, lb_il_P2 ...

the number of gul and fm are computed as fellow
        block_process_size = num_gul_per_lb + (num_fm_per_lb * (2 if ri_output else 1))
        num_lb = (max_process_id - 1) // block_process_size + 1
        num_gul_output = num_lb * num_gul_per_lb
        num_fm_output = num_lb * num_fm_per_lb

PR:
https://github.com/OasisLMF/OasisLMF/pull/628

**Comment by cdl-clgx** [comment]
@sstruzik @benhayes21 
What are `conf.ini` keywords? Are they still:
- `IL_TO_GUL_RATIO`
- `N_GUL'
?

BTW: where can I find `conf.ini` specs with keywords? Thanks

**Comment by sambles** [comment]
https://oasislmf.github.io/releases/latest_release.html#updated-worker-configuration

**Comment by cdl-clgx** [comment]
Good to know. Thanks @sambles
However, I can't find nothing about the load balancer configuration.
How can it be configured? `conf.ini`, or `oasislmf.json`? What keywords?
Thanks

**Comment by sambles** [comment]
> As a general rule all **oasislmf** command line flags can be set using either BASH or the **oasislmf.json** configuration file. For example if there was a flag --my-run-flag <val> it can be set in bash using OASIS_MY_RUN_FLAG=<val> or "my_run_flag": <val>, in json.

### oasislmf.json (Ratio 1:2)
```
{
   "ktools_num_gul_per_lb": 1,
   "ktools_num_fm_per_lb": 2,
   ... other settings ...
}
```
### Environment Vars
```
OASIS_KTOOLS_NUM_GUL_PER_LB=1
OASIS_KTOOLS_NUM_FM_PER_LB=2
```

**Side Note:** `conf.ini` has been changed to only include platform specific options, any option available in the oasislmf python package (MDK) will need to be set in oasislmf.json or as environment vars.
