### ISSUE TITLE
TypeError triggered in write_exposure_summary when _keys_errors_fp = None

### ISSUE THREAD

**Issue by hchagani-oasislmf** [OasisLMF/OasisLMF#617]
When `model_preparation/summaries:write_exposure_summary()` is called in `manager.py`, the file path for the keys errors file is submitted. This causes a problem when `model_preparation/gul_inputs:get_gul_input_items()` is called as the argument `keys_fp = _keys_errors_fp = None`. In particular the issue lies with L161 in `gul_inputs.py`:

```
    keys_error_fp = os.path.join(os.path.dirname(keys_fp), 'keys-errors.csv')
```
As `keys_fp = None`, a `TypeError` is triggered:
```
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/commit/5a3d492091ef5a8374b8e02a15d31f2e13697e34
