### ISSUE TITLE
Group perils in keys.csv return - Exposure summary 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#626]
Should the exposure summary handle group perils? 

Problem:  Combined flood model returning a group flood peril will fail to create an exposure summary
```
 warnings.warn('Column {} not found in loc file, ignoring'.format(col))
/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/summaries.py:868: UserWarning: "OO1" is not a valid OED peril ID/code. Please check the source exposure file.
```

> **benhayes21**  almost - I think it might be a bit complicated by their combined flood models not being split out to calculate loss at the sub-peril level. So they should probably just pick one (ORF or OSF) and return that. If they split it out I think they'll double their losses

> **Sam Gamble** ahh right. or we edit the exposure summary call to allow group perils if thats what the keys server returns?  I guess if its a combined peril model it might make sense to use the group code 

> **benhayes21** yes, we could do that. we might not want to include "all perils" but the grouped flood ones might make sense

**Comment by lucaspanayiotou** [comment]
Hello team, could we add this to a board? Or is it effectively already covered in:
https://github.com/OasisLMF/OasisLMF/issues/627 ??
