### ISSUE TITLE
Limit number of processes based on both number of cores and memory available

### ISSUE THREAD

**Issue by sstruzik** [OasisLMF/OasisLMF#646]
Take into account the number of cores, memory available, and total number of sub-process spawn to determine how many process are created (not just the number of core like today).

**Comment by DanielFEvans** [comment]
I'd suggest using the physical core count, not hyperthreaded core count, if Oasis' detection doesn't already do so.

I'll also note that our model software has memory-scaling behaviour built-in, meaning that as the number of processes increases, each worker will reduce its memory use, by doing smaller amounts of work at once. I don't know if any other model vendors have such a feature, but it's worth being aware that there might be two separate systems fighting against each other.

**Comment by benhayes21** [comment]
closing for now - new platform limits the problem
