### ISSUE TITLE
model settings to define relationships between event and occurrence options

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#662]
occurrence files are often tied to event set options, and it would be good if this relationship/dependency was represented in the model settings file in some way.

Example, Model A has two event sets (one probabilistic and one historical) and three occurrence files (two options for the probabilistic events and one for the historic event set). The model settings should make available this information so that a user can see which files should go together. A UI might interpret this and only allow certain combinations.

**Comment by sambles** [comment]
**Note:** one way link from event set to occurrence
