### ISSUE TITLE
fmpy numerical issues allocrule 1

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#686]
numbers are way off for a number of test cases in ktest/ftest.

Tests are;
fm4
fm5
fm6
fm7
fm8
fm9
fm11
fm12
fm13
fm14
fm15
fm16
fm17
fm19
fm21

to replicate, in
https://github.com/OasisLMF/ktest/ftests/
run
sh runtestspy.sh

then compare  control with test out:
diff ctrlpy/fm4_a1.csv testoutpy/fm4_a1.csv

Note that a0 and a2 results are all correct for the above cases.
I used oasislmf 1.12.1
please can you take a look, @sstruzik ? thanks

**Comment by sstruzik** [comment]
Thanks Joh, it should be fix with the PR, there was a mistake in the a1 code

**Comment by johcarter** [comment]
Yes that has fixed them all, thank you
