### ISSUE TITLE
Include year in ELT outputs

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/OasisLMF#691]
Our users are requesting the year as an extra column in the ELT outputs. So columns would be:

- summary_id
- type
- event_id
- **year**
- mean
- standard_deviation
- exposure_value

**Comment by johcarter** [comment]
Hi Carl, this is essentially what the period loss table is (PLT).

**Comment by carlfischerjba** [comment]
Thanks for pointing that out, Joh. I believe this provides what we need so I'll close. I've confirmed that the PLT and ELT outputs have identical losses in the same order (the only difference being the extra period and occ columns). But I must have misunderstood what the PLT was for. I thought it contained losses summed across periods/years.

**Comment by johcarter** [comment]
there was some talk of making it so, but people generally thought that keeping the losses separate by event was more useful. then you can always aggregate loss from event-year to year
