### ISSUE TITLE
FM testing and visualisation tool

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#692]
* Similar to https://github.com/OasisLMF/ReinsuranceTestTool

**Comment by johcarter** [comment]
thanks Sam
So we'd like to;
1) import OED files
2) view / edit OED files
3) view fm files 
4) see a visualisation of the hierarchy of agg_ids (and possibly also the associated layer_ids)
5) do oasislmf exposure run to produce determinstic results by location, by policy or by account

the assumption is that the test cases will be small and this will be a dev tool for our use so it needn't handle large files.
cheers
Joh
