### ISSUE TITLE
oasislmf platform api search crash when metadata is empty

### ISSUE THREAD

**Issue by s3gm3ntationFault** [OasisLMF/OasisLMF#701]
The following call to API_portfolios is generating an invalid url
`client.API_portfolios(session, url).search({})`

/v1/portfoliosNone instead of /v1/portfolios
```
def search(self, metadata):
    search_string = None
    for key in metadata:
        if not search_string:
            search_string = '?{}={}'.format(key, metadata[key])
        else:
            search_string += '&{}={}'.format(key, metadata[key])
    return self.session.get('{}{}'.format(self.url_endpoint, search_string))
```
Changing the first line
`search_string = None` to `search_string = ""` would keep the current behavior when metadata is provided and solve the error at the same time

**Comment by sambles** [comment]
Thanks for the report! I've added the suggested fix.

**Comment by s3gm3ntationFault** [comment]
I also foresee that this issue applies to the other API endpoints. 
As the search method is exactly the same on all the classes extending from ApiEndpoint the code could be moved to the super class avoiding code duplication.

**Comment by sambles** [comment]
Ah yes good point! I'll add that into the PR, thanks again
