### ISSUE TITLE
gul_errors_map contains duplicate columns: loc_id

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OasisLMF#713]
The gul_errors_map.csv contains duplicate columns of "loc_id":

**loc_id**,portnumber,accnumber,locnumber,condnumber,peril_id,coverage_type_id,**loc_id**,tiv,status
1,1,1,1,0,ORF,4,1,1000000.0,nomatch
1,1,1,1,0,OSF,4,1,1000000.0,nomatch
...

One should probably be removed or renamed?

**Comment by benhayes21** [comment]
```        # Store the gul_input_errors for debugging then reduce
        store_cols = ['loc_id', 'portnumber', 'accnumber', 'locnumber', 'condnumber']
        reduce_cols = ['peril_id', 'coverage_type_id', 'loc_id', 'tiv', 'status']
        gul_inputs_errors_df[store_cols + reduce_cols].to_csv(
            os.path.join(target_dir, 'gul_errors_map.csv'),
            index=False
        )```

**Comment by benhayes21** [comment]
change combined list to a set to remove the dupe

**Comment by DanielFEvans** [comment]
You'll need to convert back to a list before using it to select columns from Pandas - it won't let you use a set.

(Also, consider whether the order of columns actually matters - a set will lose that ordering)
