### ISSUE TITLE
Change step policy file generation and calcrules to convert % tiv to amounts in kernel inputs

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#715]
Bring step policies in line with all other policy calcrules and convert % TIV terms to amounts in the input files, to ensure they are computed deterministically (not determined by coverage losses present in the ground up loss).

In il inputs preparation
when TriggerType = 2
multiply [StepCoverage]TriggerStart by TIV
multiply [StepCoverage]TriggerEnd by TIV 
when PayoutType = 2
multiply [StepCoverage]PayoutStart by TIV
multiply [StepCoverage]PayoutEnd by TIV

StepCoverages are;
Buildings
Contents
BuildingsContents

TIV calculation for the above is
StepCoverage: Location file TIV field
Buildings: BuildingsTIV
Contents: ContentsTIV
BuildingsContents: BuildingsTIV+ContentsTIV

in calcrules_step.csv
joh to update

fmpy
change calcrules to use amounts rather than % tiv (joh to spec)

**Comment by sstruzik** [comment]
functionally fmpy is already taking the tiv from the input files and computing the %tiv term independently of the coverage losses present in the ground up loss. It is part of the fmpy pre computation step (create-financial-structure-files)

**Comment by benhayes21** [comment]
complete in fmpy
