### ISSUE TITLE
CXL risk limits not applied

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#721]
For reinsurance type 'CXL' risk limits and risk attachment terms are not supported.

Test case to be provided.

**Comment by johcarter** [comment]
721_0 is a test case where there are no risk limits, and 721 is the same with a risk limit of 1000 applied to the second reinsurance. The net result is the same for both, but the net loss should be higher for 721 because there is a limit of 1000 ceded on each account.
[721.zip](https://github.com/OasisLMF/OasisLMF/files/5819820/721.zip)
[721_0.zip](https://github.com/OasisLMF/OasisLMF/files/5819821/721_0.zip)

**Comment by johcarter** [comment]
Although its rare for CXL to have risk terms, since OED allows them then rather than fail silently, CXL should be processed in an identical way to QS and PR Reinsurance types.

**Comment by benhayes21** [comment]
duplicate - closing
