### ISSUE TITLE
Request for new Exposure output report

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#727]
Request from Swiss Re to have an output option in oasislmf to provide exposure values grouped by any field in the OED input file. This would behave like a normal report but could possibly bypass some aspects of ktools as no loss calculations are required (though maybe FM?)

From Marc:

Hi Ben

 

To make a concrete proposal:  For us it would make sense if the table   gul_S2_summary-info.csv would have an additional column providing the number for how much of the TIV could be mapped to area_peril grid points. Often this will not be the exposure (TIV) because maybe there is no mapping for CRESTA (user gives CRESTA, model is for ZIP), or the exposure is in countries outside the model domain etc (e.g. Luxembourg exposure for a Belgium model etc.).

 

Best

Marc

**Comment by sambles** [comment]
might be solved by https://github.com/OasisLMF/OasisLMF/pull/747 - need feedback from Marc
