### ISSUE TITLE
Command autocomplete

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#75]
Add auto-complete functionality to oasislmf command set, for sub-commands etc.

https://github.com/OasisLMF/OasisLMF/tree/feature/command-autocompletion

**Comment by sambles** [comment]
https://github.com/kislyuk/argcomplete

**Comment by sr-murthy** [comment]
I tried to implement this last year, using the global autocomplete option, but it didn't seem to work.

**Comment by sambles** [comment]
it would need to install a bash script and might work differently depending on the shell. 

option 1:  figure out setup.py can handle the install 
option 2: Prompt the user on first install "Install autocomplete for oasislmf? 'Y/N'"  which is something i noticed from **Travis CLI**
https://github.com/travis-ci/travis.rb/blob/master/assets/travis.sh
