### ISSUE TITLE
switch oasislmf exposure run to use gul stream type 2

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#750]
we are generating the raw_guls binary for deterministic testing using stream type 1 (default) whereas we need to be testing stream type 2 because type 1 is no longer used for most models and deprecated in ktools.

the command for generating guls binary is ;

gultobin -S{number of loss factors} -t2 < raw_guls.csv > raw_guls.bin

where t2 is stream type 2

we also need to generate the raw_guls.csv in a different order. currently its

event_id, item_id, sidx, loss
1,1,-1,0
1,1,-2,0
1,1,-3,10000
1,1,1,10000

and it needs to be 

event_id, item_id, sidx, loss
1,1,-3,10000
1,1,-2,0
1,1,-1,0
1,1,1,10000

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/commit/42129ea745598fceeecae9f5db93ec9a73c69690
