### ISSUE TITLE
Performance tools

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#78]
It would be very useful for model developers to have some performance tools for analyzing their model. The base line functionality would be a breakdown of run time by keys lookup and each of the run time steps. More advanced features could include:
- Other instrumentation e.g. memory pressure
- Parameter sweep of num simulations, locations
- Automated exposure generation for various sized portfolios, based on area perils and vulnerabilities.

**Comment by sr-murthy** [comment]
I think this is a good idea. I think it would be relatively easy to add a module to the existing `oasislmf.utils` subpackage containing methods to test various performance or compute runtime metrics. But this would need to be sketched out a bit first, to what we need or the suppliers would want.
