### ISSUE TITLE
GEM: No data returned from keys service

### ISSUE THREAD

**Issue by AntonioPetruccelli** [OasisLMF/OasisLMF#795]
Hi, when trying to change inside the oasislmf.json the exposure input file (modifying mainly the location), from the provided Dominican Republic sample, I get the "No data returned from keys service" error. I guess a different "areaperil_dict.csv" has to be provided. Is there a way to generate such file? 

Thanks in advance

**Comment by sambles** [comment]
Hello @AntonioPetruccelli  looking at the GEM lookup code, areaperil is matched by `lat/long`  with fallback options for `county` and `state`.  https://github.com/OasisLMF/gem/blob/master/src/keys_server/GMO/utils/AreaPerilLookup.py#L100-L123 

where `GeogName1 == county`  and `AreaName1 == state`

Did you get a look at the keys error file to confirm that was the problem? 

**Example**
```
$ oasislmf model generate-keys --oed-location-csv <path-to-new-loc-file>

Stating oasislmf command - GenerateKeys
RUNNING: oasislmf.manager.interface
site-packages/oasislmf/__init__.py:63: UserWarning: imports from 'oasislmf.model_preparation' are deprecated. Import by using 'oasislmf.preparation' instead.
  warnings.warn(deprecated)
RUNNING: GMO.GMOKeysLookup.process_locations
Keys successful: runs/keys-20210318104059/keys.csv generated with 0 items
Keys errors: runs/keys-20210318104059/keys-errors.csv generated with 10 items



$ head -3 runs/keys-20210318104059/keys-errors.csv
LocID,PerilID,CoverageTypeID,Status,Message
10,QEQ,1,nomatch,No area peril or vulnerability match
7,QEQ,1,nomatch,No area peril or vulnerability match
```

**Comment by AntonioPetruccelli** [comment]
The key-error file is not created yet.  The output is : 

Stating oasislmf command - RunModel
RUNNING: oasislmf.manager.interface
  0%|                                                                                             | 0/2 [00:00<?, ?it/s]
Processing arguments - Creating Oasis Files

Generating Oasis files (GUL=True, IL=True, RIL=False)
/home/.../.local/lib/python3.8/site-packages/oasislmf/__init__.py:63: UserWarning: imports from 'oasislmf.model_preparation' are deprecated. Import by using 'oasislmf.preparation' instead.
  warnings.warn(deprecated)
  0%|                                                                                             | 0/2 [00:01<?, ?it/s]
No data returned from keys service

**Comment by sambles** [comment]
There should be something returned even with no matches, are you able to share the first 10 rows of your location file?

**Comment by AntonioPetruccelli** [comment]
Sure, it is a slight modification of the sample dom-rep dataset, for testing purpose: 

LocCurrency,PortNumber,AccNumber,LocNumber,GeogName1,AreaName1,Latitude,Longitude,CountryCode,ConstructionCode,OccupancyCode,YearBuilt,YearUpgraded,NumberOfStoreys,NumberOfBuildings,LocPerilsCovered,BuildingTIV
--
n/a,1,146,10527,Roma,Lazio,41.88561,12.54355,IT,5100,1050,1800,1900,1,1,QEQ,12009600
n/a,1,146,10526,Roma,Lazio,41.88224,12.54122,IT,5100,1100,1900,1900,2,1,QEQ,3602880
n/a,1,146,10525,Roma,Lazio,41.88992,12.54224,IT,5100,1050,1850,1900,2,1,QEQ,6894720
n/a,1,146,10524,Roma,Lazio,41.88790,12.54987,IT,5100,1050,1900,1900,3,1,QEQ,9054720
n/a,1,146,10523,Roma,Lazio,41.88567,12.54117,IT,5100,1100,1900,1900,3,1,QEQ,3404160
n/a,1,146,10522,Roma,Lazio,41.88123,12.54465,IT,5100,1050,1800,1900,3,1,QEQ,5063040
n/a,1,146,10521,Roma,Lazio,41.88113,12.54220,IT,5100,1100,1900,1900,2,1,QEQ,2928960
n/a,1,146,10520,Roma,Lazio,41.88219,12.54112,IT,5100,1050,1900,1900,1,1,QEQ,2833920
n/a,1,146,10519,Roma,Lazio,41.88334,12.54887,IT,5100,1050,1900,1900,3,1,QEQ,557654.4
n/a,1,146,10518,Roma,Lazio,41.88333,12.54661,IT,5100,1050,1900,1900,2,1,QEQ,1997568

**Comment by sambles** [comment]
The `ConstructionCode` + `NumberOfStoreys` column values in your location file are not supported by the GEM lookup, so the invalid rows get filtered out --> no results to return.  Not really the best behavior from the GEM lookup code, id expect it to mark the row as `failed` and add an error message. 

[Problem happens here](https://github.com/OasisLMF/gem/blob/master/src/keys_server/GMO/GMOKeysLookup.py#L219-L221)
```
gem_taxonomy_by_oed_occupancy_and_number_of_storeys_df[['constructioncode', 'numberofstoreys']]
   constructioncode  numberofstoreys
0              5156                1
1              5150                2
2              5150                3
3              5150                1
4              5109                2
5              5109                3
6              5109                1
7              5105                1
8              5105                2
9              5105                3
10             5101                2
11             5103                1
12             5103                2
13             5000                1
14             5050                1
15             5050                2
16             5050               -1
```

If you edit the loc file to use something from the table above it should return as `nomatch`,  to get a success you'll need a location within scope of the model (Dominican republic)
