### ISSUE TITLE
Issue in coverage_type_id grouping of ground up loss results for multi-peril

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#816]
Issue found in piwind when running gul outputs by coverage.

it seems that losses are being grouped by subperil instead of by coverage
attached files are
* the gul_summary_map showing that items 1 and 3 are coverage 1, and items 2 and 4 are coverage 3.
* the gulsummaryxref grouping items 1 and 2 to summary_id 1 and 3 and 4 to summary_id 2.
* analysis_settings.json
* location
* account
* items

The correct grouping in gulsummaryxref is items 1 and 3 to summary_id 1  and items 2 and 4 to summary_id 2.

to replicate, run piwind 10 locations with the following oed fields specified:
    "gul_summaries": [
        {
            "oed_fields": ["PortNumber", "AccNumber", "LocNumber", "coverage_type_id"],

**Comment by johcarter** [comment]
[oasislmf816.zip](https://github.com/OasisLMF/OasisLMF/files/6359189/oasislmf816.zip)

**Comment by johcarter** [comment]
@sambles please could you take a look?

**Comment by sambles** [comment]
Looks to be a column sorting issue when using `fm_summary_map` for creating gul summary groups.  I've opened a PR with a fix here: https://github.com/OasisLMF/OasisLMF/pull/817
