### ISSUE TITLE
Mismatch between ReinsuranceType Strings in OED spec and Oasis implementation

### ISSUE THREAD

**Issue by jonathanbethel** [OasisLMF/OasisLMF#87]
When testing out 0.395.3 I have noticed that the constants

REINS_TYPE_CAT_XL = "CAT XL"
REINS_TYPE_AGG_XL = "XL"

in the OED.py file do not match with the OED Spec, which specifies that these should be 'CXL' and 'AXL' respectively. 

This leads to Flamingo Server failing when 'CXL' is used over 'CAT XL'

**Comment by mpinkerton-oasis** [comment]
Small fix - will aim to include in next (November) release.
