### ISSUE TITLE
Add 'issue' regression cases to fm testing 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#873]
## Issue Description
Test stored in [validation/issues](https://github.com/OasisLMF/OasisLMF/tree/master/validation/issues) aren't currently check when running the package testing. 

- [x] The file formats are inconsistent and need aligning 
- [x] Combine into single test case 
- [x] Joh to review

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/tree/master/validation/issues/828

**Comment by johcarter** [comment]
hey @sambles please can you test this for me? tests/fm/ pytest now has an issues test
My branch is
``feature/873-automated-issues-tests``
pytest is not recognising the expected folder ``issues/expected`` hence the issues test is failing. Is this the same for you?
thanks!

**Comment by sambles** [comment]
@johcarter 
I think the keys return was missing the 2nd peril_id, its tripping over at:  
```
FAIL: generated /home/sam/repos/core/oasisLMF/validation/runs/test-fm-p2-issues-20210713163233/keys.csv vs expected /ho
.. etc
```

I've added what the tests are expecting to this commit: https://github.com/OasisLMF/OasisLMF/commit/55d02161fc209551f091df6c3801fdf2167e2c34 

Do the changed files look consistent?

**Comment by sambles** [comment]
With that change pytest does run ok for me
```
tests/fm$ pytest 
===========================================================================
platform linux -- Python 3.8.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/sam/repos/core/oasisLMF, configfile: setup.cfg
plugins: cov-2.12.1, hypothesis-6.14.2, ignore-flaky-2.0.0
collected 18 items                                                                                                                                                                                                                                                                         

test_fm.py .........                                                                                                                                                                                                                                                                
test_fmpy.py .........                  
```

**Comment by johcarter** [comment]
all tests are failing for me now. its difficult to tell why, but something to do with the location of the validation folder.  
E                   oasislmf.utils.exceptions.OasisException: The path /home/joh/dev/OasisLMF_branch/tests/fm/validation (Test directory - should contain test directories containing OED files and expected results) must exist for Computation Step RunFmTest

**Comment by johcarter** [comment]
all tests pass on a clean branch. @sambles please could you review the PR?

**Comment by johcarter** [comment]
This is complete on branch `feature/873-automated-issues-tests`. one enhancement to make on the branch before merging #885
