### ISSUE TITLE
Limit number of ktools execution pipes based on number of events

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#876]
## Issue Description

> **Request:** There is the option `--ktools-num-processes` but its not quite what we're looking for since it needs to be specified by the user up-front. Would be nice to let the lookup stage figure out how many events there are or how big some other piece of data is based on some (possibly complex) calculation and decide the number of processes based on that. No urgent need for that though.

Check the selected events file size to workout the number of events to be processed, and limit the number of execution pipes needed.  

**example**
```
import os
event_num_bytes = os.path.getsize("./events_p.bin")
num_events = event_num_bytes / 4
```

**Comment by benhayes21** [comment]
closing
