### ISSUE TITLE
inconsistent assignment of group_id in items file leads to non-repeatable results for the same input

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#892]
## Issue Description

It has been observed that group_id in the items file isn't being assigned consistently for the same set of input files for a few models.  This leads to non-repeatable results for some runs. It seems to be an intermittent problem.

The two models it has been observed for are both complex models. Is the code for group_id assignment in the core code base though? For investigation.

**Comment by sambles** [comment]
Issue seemed to be cause by this line in the `model_settings.json` file: 
```
 "data_settings": {                                                                                                                       
        "group_fields": ["PortNumber", "AccNumber", "LocNumber"]
    }  
```

Removing the `group_fields` setting seems to yield consistent `group_id` values in the **items.csv** file

**Comment by sambles** [comment]
problem seems to stem from this call to `factorize_ndarray` when the number of group_id columns is greater than 1: 
https://github.com/OasisLMF/OasisLMF/blob/master/oasislmf/preparation/gul_inputs.py#L320-L325

setting ` sort_opt=False` seems to assign consistent group_id's  but i'm not sure if setting this causes a breakage somewhere else
