### ISSUE TITLE
Support for monetary / absolute damage functions

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#902]
## Issue Description

The standard kernel components only supports relative damage functions. This means that a relative damage ratio is sampled in the ground up loss calculation and then multiplied by the TIV to produce GUL.  The requirement is for Oasis to support absolute or monetary damage functions.

Nazare task_ID 303 delivery phase 4

Uses cases provided: 
1) Flood damage is modelled on a loss per square metre basis.  The requirement is to support damage functions which define loss per square meter as a function of intensity. The loss per square metre can then  be scaled by the floor area 
2) For the small claims from perils such as hail, the loss amount isn’t really proportional to the building value.
Instead it could be the cost of broken windows, some roofing sheets and maybe 2 or 3 days from tradesmen to do the work.
Often there is a fixed cost for a building inspection or regulatory council signoff too. Is there a way to model a range of small fixed amounts?
 

Tasks to complete

- [ ] Define requirements
- [ ] Design
- [ ] Implementation

**Comment by johcarter** [comment]
damage bin dict example

![image](https://user-images.githubusercontent.com/11421733/200567490-481500f0-2299-4188-bbee-ea5a5dc01829.png)

vulnerability example.  id 1 is a relative function, id 2 is a monetary function

![image](https://user-images.githubusercontent.com/11421733/200567939-bc9a6e9f-c89e-40ca-a796-710b34ea5160.png)

**Comment by johcarter** [comment]
please could you review @benhayes21 @sstruzik @mtazzari ?

**Comment by benhayes21** [comment]
need to consider currencies
