### ISSUE TITLE
improve correlation functionality available through the engine

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#910]
## Issue Description

improve correlation functionality available through the engine
Nazare Workflow_Id 1000 Task_Id 1003

**Comment by johcarter** [comment]
Needs clarification from steering group

**Comment by johcarter** [comment]
[correlation_proposals_v1_shared.pdf](https://github.com/OasisLMF/OasisLMF/files/8762052/correlation_proposals_v1_shared.pdf)

**Comment by mtazzari** [comment]
Done
