### ISSUE TITLE
ensure that losses are repeatable (compilation version rng)

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#912]
## Issue Description

ensure that losses are repeatable (compilation version rng)
Nazare Workflow_Id 1000 Task_Id 1008

**Comment by johcarter** [comment]
Two aspects of repeatable losses are
1) The compiler version of c++ gulcalc binary affects the random numbers generated. ktools binaries are built and shipped within the platform. All else equal, the indivdual ground up loss samples for the same portfolio on two different environments which use the standard binaries will be identical because the random numbers are identically seeded.
On an environment which does not use the shipped binary, where the gulcalc binary has been compiled differently, then the losses may be different to those being run on a environment with the standard build, for the same input.

- [ ] Investigate alternative RNGs and consistency across compilers

2) Within an environment, random numbers are seeded based on the event_id, sample index (sidx) and a group_id. This means two items (representing a coverage-peril) that share the same group_id will use the same set of random numbers for a given event and sample size.  However the group_id is an index number which is assigned dynamically per analysis, and is not consistent for the same location across analyses. This means that the same location will have a different set of losses when it appears in two different portfolios.

There are three ways that consistent assignment of group_id can be achieved.
1) Change the default assignment of group_id to be deterministic based on the PortNumber, AccNumber, LocNumber. Unless there is a good reason not to, make this a 4-byte integer to fit standard kernel input format.
2) Model develop specifies the rule to generate group_id , for example by areaperil_id, by location, or other. This can be done in the model settings file.
3) User can specify CorrelationGroup in the OED input files to override either of the two above defaults. The value should be a 4 byte integer.

- [ ] Implement 1 as default group_id generation in oasis file generation, in the absence of any rule specfied in 2.

**Comment by hchagani-oasislmf** [comment]
Regarding consistency across compilers, while the generator (in this case the Mersenne Twister 19937) will generate the same values, the distributions (in this case `std::uniform_real_distribution`) may not across different compilers. There is no standard behaviour for these distributions. If we want to standardise this across all compilers, we will need to define our own distribution. @johcarter, would you like me to look into this? If so, we can open an issue in the `ktools` repo and I can work on it.

**Comment by johcarter** [comment]
Hi @hchagani-oasislmf if you could estimate the effort required that would be a good start please. It would need to be as performant as the current method.

**Comment by johcarter** [comment]
part 2 is code complete. no specific problems known for part 1 (compilation version). tests need to be defined
