### ISSUE TITLE
Loss is not init to 0 for step policy

### ISSUE THREAD

**Issue by sstruzik** [OasisLMF/OasisLMF#944]
## Issue Description
When using step policy, loss is accumulated through event instead. It needs to be initialized.

## Steps to Reproduce (Bugs only)

1. have a node with step policy 27 with step id 1 and multiple event

## Version / Environment information
oasislmf 1.15.18 and develop

**Comment by johcarter** [comment]
In fmpy, the step policy calcrules were not being initialised, meaning they were not being reset to zero between events. This meant that the gross losses were wrong for any model run with more than one event. This affected all of the step policy calcrules.
