### ISSUE TITLE
Output summaries in MDK

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#95]
Currently the MDK only outputs at portfolio level i.e. all losses grouped up. This need to replicate, at the minimum, the Flamingo functionality where a summary level can be picked from a predefined set for GUL, IL and RI losses. The current set supported in Flamingo is:

Prog, Policy, State, County, Location, LOB

We should also conider making this more generic i.e. any combination of OED exposure fields can define a summary set.

**Comment by sr-murthy** [comment]
I don't fully understand how output aggregation works at the domain level, but in terms of code I assume this refers to the function of the `summary_id` and/or `summaryset_id` fields in the GUL items that the MDK exposure manager generates. Here's the relevant bit of code

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/exposures/manager.py#L867

At the moment both these fields are set to `1`. I assume you want these values to be customisable based on, say, appropriate keys in the analysis settings JSON.
