### ISSUE TITLE
Stochastic disaggregation feature

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#956]
## Issue Description

Define and implement stochastic disaggregation
 Nazare Workflow_id 1000 Task_id 1006 phase 4

Uncertainty about the exposures is not generally captured in loss output. We make a pick of areaperil and vulnerability which together determine  a fixed effective damage distribution (per event) in Oasis. But other choices of areaperil_id and vulnerability_id might be valid, and might produce a different damage distribution and therefore different losses. The question is how should we capture this uncertainty in the modelling process?

Use case 1 – location geography uncertainty
Site of building is known at a lower resolution than model hazard (for example, building location defined at postcode level, model hazard at 30m grid cell resolution.) This means that we are uncertain about what hazard intensity the building will  experience because we are uncertain where the building is in relation to the event footprint. This is critical for perils such as flood, where it really matters if the building is on a flood plain vs on a hill, for example.

Use case 2 – location vulnerability type is unknown.
We don’t know characteristics such as construction type, number of storeys, occupancy type that we would need to pick a vulnerability function. There may be an ‘unknown’ vulnerability option provided by the modeller, or it may not be modelled at all.

Use case 3 – combination of geography and vulnerability characteristics unknown

Use case 4 – aggregate data
One line in the location file represents multiple sites, each with geography and vulnerability uncertainty as above.

**Comment by johcarter** [comment]
[disaggregation_proposals_v3_shared.pdf](https://github.com/OasisLMF/OasisLMF/files/10067950/disaggregation_proposals_v3_shared.pdf)

**Comment by mtazzari** [comment]
Tracking progress on all agreed implementations:

- [ ] https://github.com/OasisLMF/OasisLMF/issues/1126
- [ ] https://github.com/OasisLMF/OasisLMF/issues/1124
- [ ] https://github.com/OasisLMF/OasisLMF/issues/1123
- [ ] https://github.com/OasisLMF/OasisLMF/issues/1125
- [ ] https://github.com/OasisLMF/OasisLMF/issues/1127

**Comment by benhayes21** [comment]
user controls on backlog - closing
