### ISSUE TITLE
Reinsurance prep won't run with pandas 1.4.0

### ISSUE THREAD

**Issue by carlfischerjba** [OasisLMF/OasisLMF#975]
`pd._lib` appears to be [no longer available](https://github.com/pandas-dev/pandas/blob/1.4.x/pandas/__init__.py#L34) in Pandas >=1.4.0. Might still be available via `pd._libs.lib`. Or pandas version could be pinned.

https://github.com/OasisLMF/OasisLMF/blob/43a9ea0f2d0fa97c6ef7710e2689c67d00750616/oasislmf/preparation/reinsurance_layer.py#L633

**Comment by sambles** [comment]
Quick note, a fix for this issue was added in [PR973](https://github.com/OasisLMF/OasisLMF/pull/973) via 
https://github.com/OasisLMF/OasisLMF/pull/973/commits/76721f7e89fa5fa805ab8fc0c2632a36146d2f04

And should make it into both, `LTS 1.23.x` and the next monthly release `1.25.0`
