### ISSUE TITLE
Peril Specific Runs

### ISSUE THREAD

**Issue by benhayes21** [OasisLMF/OasisLMF#992]
## Issue Description
enhancement - can we add in functionality to allow peril specific runs using the gul mapping table and getmodel? Model Settings should be used to present options for peril filters.

With the introduction of peril correlation, we now should have the list of perils covered by the model in the model setting in the lookup_settings  section.
ex:
    "lookup_settings":{
        "supported_perils":[
           {"id": "WSS", "desc": "Single Peril: Storm Surge", "peril_correlation_group":  1},
           {"id": "WTC", "desc": "Single Peril: Tropical Cyclone", "peril_correlation_group":  2},
           {"id": "WW1", "desc": "Group Peril: Windstorm with storm surge", "peril_correlation_group":  3}
        ]
    },
This could be retrieved and made available in the UI to provide filtering option

The filtering itself needs to be done in the computation step not in the preparation step because we want to be able to have multiple computation with different peril filter using the same preparation files. It is also in line with several custom model and gulcalc already available.

- [x]  add filter in modelpy
- [x] add filter to gulpy
add a flag --perils in modelpy and gulpy that will filter any perils not present in the perils list.
to do so we also need to load the keys file and extract all valid areaperil_id

**Comment by sstruzik** [comment]
in order to filter peril in getmodel we can retrieve the list of (CoverageTypeID	AreaPerilID	VulnerabilityID) to keep from the file "keys.csv" based on the peril filter. Then filter those when reading the item file in load_items.
